### ISSUE TITLE
test_prints_labels_if_given_on_failure is flaky

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis#1080]
```
=================================== FAILURES ===================================
____________________ test_prints_labels_if_given_on_failure ____________________
[gw15] linux -- Python 3.6.4 /usr/bin/python
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-python-3.44.21/tests/cover/test_arbitrary_data.py", line 67, in test_prints_labels_if_given_on_failure
    assert 'Draw 1 (Some numbers): [0, 0]' in result
AssertionError: assert 'Draw 1 (Some numbers): [0, 0]' in ''
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-python-3.44.21/tests/common/utils.py", line 52, in raises
    assert False, "Expected to raise an exception but didn't"
AssertionError: Expected to raise an exception but didn't
```

**Comment by Zac-HD** [comment]
Should have known that would work: https://ci.appveyor.com/project/DRMacIver/hypothesis/build/1.0.33/job/r125xp3i65wdiojp#L606

**Comment by felixonmars** [comment]
Thanks a lot!

**Comment by Zac-HD** [comment]
No problem!
