### ISSUE TITLE
strategies.from_type doesn't work for the empty tuple type

### ISSUE THREAD

**Issue by lubieowoce** [HypothesisWorks/hypothesis#1583]
## `strategies.from_type(typing.Tuple[()])` should return `()`, but crashes instead

Python==3.5.4, hypothesis==3.71.3

First of all, I know this is a bit silly, since there is only one possible empty tuple, `()`, and hence not much to generate. It's also a pretty niche concern, but I think it'd be nice to support this for completeness. 

According to the `mypy` [docs](https://mypy.readthedocs.io/en/latest/builtin_types.html), the empty tuple has type `typing.Tuple[()]`. (I couldn't find anything on this in the `typing` docs, but since Guido reviewed and merged [the commit](https://github.com/python/mypy/commit/71332d5857b36f4fa7e389bf9bf2c95776cd26f0) to `mypy's` docs ,  `Tuple[()]` seems like the official way to do it.)

On my machine, `from_type(Tuple[()])` crashes like this:
```python
>>> from typing import Tuple
>>> from hypothesis.strategies import from_type
>>> from_type(Tuple[()]).example()
Traceback (most recent call last):
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 131, in recur
    result = mapping[strat]
KeyError: tuples(deferred(lambda: func(*args, **kwargs)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 131, in recur
    result = mapping[strat]
KeyError: tuples(deferred(lambda: func(*args, **kwargs)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 304, in example
    phases=tuple(set(Phase) - {Phase.shrink}),
  File "<venv path>\lib\site-packages\hypothesis\core.py", line 979, in find
    specifier.validate()
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 380, in validate
    self.is_empty
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 142, in accept
    recur(self)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 139, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\deferred.py", line 81, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\strategies.py", line 139, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\lazy.py", line 90, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\lazy.py", line 106, in wrapped_strategy
    unwrap_strategies(s) for s in self.__args)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\lazy.py", line 106, in <genexpr>
    unwrap_strategies(s) for s in self.__args)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\lazy.py", line 48, in unwrap_strategies
    result = unwrap_strategies(s.wrapped_strategy)
  File "<venv path>\lib\site-packages\hypothesis\searchstrategy\deferred.py", line 45, in wrapped_strategy
    result = self.__definition()
  File "<venv path>\lib\site-packages\hypothesis\strategies.py", line 1200, in <lambda>
    return deferred(lambda: func(*args, **kwargs))
  File "<venv path>\lib\site-packages\hypothesis\strategies.py", line 1261, in from_type
    raise InvalidArgument('thing=%s must be a type' % (thing,))
hypothesis.errors.InvalidArgument: thing=() must be a type
```

**Comment by Zac-HD** [comment]
Thanks for reporting this @lubieowoce - I don't think it's silly at all!  If we're going to infer strategies from type hints, we should do it *properly* and not leave out any edge cases.

**Comment by lubieowoce** [comment]
Thank you for the quick response! If you're busy with other work, let me know – I'm not familiar with the codebase, but this looks like a small change, so I can try and submit a fix.

**Comment by Zac-HD** [comment]
Ah, sorry @lubieowoce - it was small enough, and your report so good (😍) that I just wrote the patch.  If you're interested in contributing beyond just seeing this fixed, I'd be happy to help you pick and issue and troubleshoot any problems though!

**Comment by lubieowoce** [comment]
No problem. I don't think I'll be able to contribute to anything bigger right now, but thanks for the offer! If I could take up a bit more of your time, I have a question – do you have any estimates on when this could land in a release? It's not blocking me on anything, as I can work around the issue quite easily, I'm just curious about your release process.

**Comment by Zac-HD** [comment]
Our release process is "automatically release every pull request", so it will be on PyPI 15-20 minutes after it's reviewed and merged!  Looking at recent dates in [our changelog](https://hypothesis.readthedocs.io/en/latest/changes.html) should show the typical cadence.

Of course I can't review my own PRs, but it's a small enough patch that even with most of the other maintainers at PyCon UK I'd expect this to be merged later this week.
