### ISSUE TITLE
test_can_specify_start_rule is flaky on Python 2

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1775]
Example failing build: https://circleci.com/gh/HypothesisWorks/hypothesis/6178?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```python
[gw1] darwin -- Python 2.7.14 /Users/distiller/project/hypothesis-python/.tox/py27-full/bin/python
Traceback (most recent call last):
  File "/Users/distiller/project/hypothesis-python/tests/lark/test_grammar.py", line 61, in test_can_specify_start_rule
    "start, type_",
  File "/Users/distiller/project/hypothesis-python/.tox/py27-full/lib/python2.7/site-packages/hypothesis/core.py", line 965, in wrapped_test
    state.run()
  File "/Users/distiller/project/hypothesis-python/.tox/py27-full/lib/python2.7/site-packages/hypothesis/core.py", line 682, in run
    falsifying_example.__expected_traceback,
  File "/Users/distiller/project/hypothesis-python/.tox/py27-full/lib/python2.7/site-packages/hypothesis/core.py", line 558, in execute
    result = self.test_runner(data, run)
  File "/Users/distiller/project/hypothesis-python/.tox/py27-full/lib/python2.7/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
    return function(data)
  File "/Users/distiller/project/hypothesis-python/.tox/py27-full/lib/python2.7/site-packages/hypothesis/core.py", line 556, in run
    return test(*args, **kwargs)
  File "/Users/distiller/project/hypothesis-python/tests/lark/test_grammar.py", line 61, in test_can_specify_start_rule
    "start, type_",
  File "/Users/distiller/project/hypothesis-python/.tox/py27-full/lib/python2.7/site-packages/hypothesis/core.py", line 517, in test
    result = self.test(*args, **kwargs)
  File "/Users/distiller/project/hypothesis-python/tests/lark/test_grammar.py", line 76, in test_can_specify_start_rule
    assert isinstance(value, type_)
AssertionError: assert False
 +  where False = isinstance(10000000000000000000L, (<type 'int'>, <type 'float'>))
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_can_specify_start_rule(data=data(...), start='NUMBER', type_=(int, float))
Draw 1: u'10000000000000000000'
```

Python 2 problem I think. You needed to use `integer_types` instead of `int` there.

**Comment by Zac-HD** [comment]
Whoops :disappointed:
