### ISSUE TITLE
Weird tooling crashes: module 'sys' has no attribute 'real_prefix'

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1777]
Every now and then my local setup gets into a broken state where trying to use `build.sh` has the following error: 

```
Traceback (most recent call last):
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/site-packages/pip/commands/install.py", line 350, in run
    isolated=options.isolated_mode,
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/site-packages/pip/commands/install.py", line 436, in get_lib_location_guesses
    scheme = distutils_scheme('', *args, **kwargs)
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/distutils/command/install.py", line 284, in finalize_options
    (prefix, exec_prefix) = get_config_vars('prefix', 'exec_prefix')
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/distutils/__init__.py", line 105, in sysconfig_get_config_vars
    real_vars = old_get_config_vars(*args)
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/distutils/sysconfig.py", line 493, in get_config_vars
    srcdir = os.path.dirname(get_makefile_filename())
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/distutils/sysconfig.py", line 240, in get_makefile_filename
    lib_dir = get_python_lib(plat_specific=0, standard_lib=1)
  File "/home/david/.cache/hypothesis-build-runtimes/python-versions/3.6.5/lib/python3.6/distutils/__init__.py", line 94, in sysconfig_get_python_lib
    prefix = sys.real_prefix
AttributeError: module 'sys' has no attribute 'real_prefix'
```
I don't currently know how to fix this other than nuking the runtimes directory.

I believe it is related to the `"The virtualenv distutils package at %s appears to be in the same location as the system distutils?"` warning that we get in our build at the moment. My suspicion is that something is causing Python to behave like it's running in a virtualenv when it's not actually running in a virtualenv, but I don't know what that might be.

**Comment by Zac-HD** [comment]
Yeah, I have no idea either - in #1684 we just disabled most caching on CI because it wasn't speeding things up either.

**Comment by DRMacIver** [comment]
> Yeah, I have no idea either - in #1684 we just disabled most caching on CI because it wasn't speeding things up either.

The situation is very different with local use, especially on Linux (where the Pythons have to be built from source). It's a 5-10 minute wait every time I have to rebuild from scratch.

**Comment by Zac-HD** [comment]
https://discuss.python.org/t/pip-make-pip-require-virtualenv-the-default/3776/16

So we probably need to update `virtualenv` or switch to `python -m venv`?

**Comment by Zac-HD** [comment]
This seems to have been related to a transition between old and new(er) virtualenv and venv toolchains - see https://stackoverflow.com/a/1883251/9297601.  Closing because I haven't seen it in some time, and `pip install -U virtualenv` seems to fix it.

**Comment by matt-uib** [comment]
I had this error in vs code in debugpy while debugging a plotly dash app and the only reason was that i at some time in the past enabled breaking on "Raised Exceptions" in vs code. So the exception was shown, but there was no real problem, as it was handled. Maybe someone had the same problem...

<img width="228" height="112" alt="Image" src="https://github.com/user-attachments/assets/935c3f91-7e78-416c-9335-9fbe2f2c0a89" />
