### ISSUE TITLE
Flaky failure in test_saves_failing_example_in_database

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1903]
```
$ pytest tests/cover/test_stateful.py --hypothesis-seed=190426488230690449493851980638261862108
============================= test session starts ==============================
platform darwin -- Python 3.7.2, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/var/folders/54/vs3dcnhx7rlddhj58w5mzlz40000gn/T/tmp74obdby0/examples')
rootdir: /Users/stuart/Dev/hypothesis, inifile: pytest.ini
plugins: xdist-1.27.0, forked-1.0.2, flaky-3.5.3, hypothesis-4.14.1
collected 63 items                                                             

tests/cover/test_stateful.py .................................F......... [ 68%]
....................                                                     [100%]

=================================== FAILURES ===================================
____________________ test_saves_failing_example_in_database ____________________
Traceback (most recent call last):
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/tests/cover/test_stateful.py", line 603, in test_saves_failing_example_in_database
    assert any(list(db.data.values()))
AssertionError: assert False
 +  where False = any([])
 +    where [] = list(dict_values([]))
 +      where dict_values([]) = <built-in method values of dict object at 0x10ab1dd38>()
 +        where <built-in method values of dict object at 0x10ab1dd38> = {}.values
 +          where {} = InMemoryExampleDatabase({}).data
----------------------------- Captured stdout call -----------------------------
Falsifying example: run_state_machine(factory=SetStateMachine, data=data(...))
Step #1: (False, 1)
Step #2: (False, 1)
Step #3: (True, 1)

You can reproduce this example by temporarily adding @reproduce_failure('4.14.1', b'AAEBAQABAQEA') as a decorator on your test case
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/tests/common/utils.py", line 77, in raises
    yield e
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/tests/cover/test_stateful.py", line 602, in test_saves_failing_example_in_database
    run_state_machine_as_test(SetStateMachine, Settings(database=db))
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 131, in run_state_machine_as_test
    run_state_machine(state_machine_factory)
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 89, in run_state_machine
    @given(st.data())
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1017, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/tests/cover/test_stateful.py", line 79, in execute_step
    assert value not in self.elements
AssertionError: assert 1 not in [1]
 +  where [1] = <tests.cover.test_stateful.SetStateMachine object at 0x10ae88080>.elements
===Flaky Test Report===


===End Flaky Test Report===
========================== slowest 20 test durations ===========================
2.15s call     hypothesis-python/tests/cover/test_stateful.py::test_bad_machines_fail[RoseTreeStateMachine]
0.68s call     hypothesis-python/tests/cover/test_stateful.py::TestMachineUsingMultiple::runTest
0.53s call     hypothesis-python/tests/cover/test_stateful.py::TestMachineWithConsumingRule::runTest
0.41s call     hypothesis-python/tests/cover/test_stateful.py::test_removes_needless_steps
0.27s call     hypothesis-python/tests/cover/test_stateful.py::test_multiple_rules_same_func
0.23s call     hypothesis-python/tests/cover/test_stateful.py::TestGivenLike::runTest
0.23s call     hypothesis-python/tests/cover/test_stateful.py::test_bad_machines_fail[BalancedTrees]
0.21s call     hypothesis-python/tests/cover/test_stateful.py::test_bad_machines_fail[DepthMachine]
0.19s call     hypothesis-python/tests/cover/test_stateful.py::test_always_runs_at_least_one_step
0.19s call     hypothesis-python/tests/cover/test_stateful.py::test_invariant_precondition
0.14s call     hypothesis-python/tests/cover/test_stateful.py::test_bad_machines_fail[OrderedStateMachine]
0.12s call     hypothesis-python/tests/cover/test_stateful.py::test_prints_equal_values_with_correct_variable_name
0.09s call     hypothesis-python/tests/cover/test_stateful.py::test_can_run_with_no_db
0.09s call     hypothesis-python/tests/cover/test_stateful.py::test_bad_machines_fail[SetStateMachine]
0.09s call     hypothesis-python/tests/cover/test_stateful.py::test_saves_failing_example_in_database
0.08s call     hypothesis-python/tests/cover/test_stateful.py::test_initialize_rule
0.07s call     hypothesis-python/tests/cover/test_stateful.py::TestDoesNotFail::runTest
0.07s call     hypothesis-python/tests/cover/test_stateful.py::TestGoodSets::runTest
0.07s call     hypothesis-python/tests/cover/test_stateful.py::test_can_explicitly_pass_settings
0.07s call     hypothesis-python/tests/cover/test_stateful.py::test_bad_machines_fail[NotTheLastMachine]
===================== 1 failed, 62 passed in 8.10 seconds ======================
```

**Comment by Zalathar** [comment]
This was originally caused by a real flaky error, but it turns out that the symptoms seen here are just a side-effect of the fact that specifying a seed prevents writes to the database, violating the assumptions of the test.

I can't seem to reproduce the original issue, even after force-enabling the database (by making `database_key` independent of `global_force_seed`), so this issue is probably not useful to anyone.

**Comment by Zalathar** [comment]
I did have the follow-up idea of modifying DB-related tests to explicitly override the “no DB while seeded” behaviour, to avoid spurious failures.

(This would be achieved via an `allow_db_while_seeded` global in `hypothesis.core` that tests would monkeypatch to `True` when needed.)

However, there are enough tests in the suite that fail under `--hypothesis-seed` that it's more than I want to take on at the moment.
