### ISSUE TITLE
`test_deadlines_participate_in_shrinking` is flaky

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1970]
```python-traceback
___________________ test_deadlines_participate_in_shrinking ____________________
Traceback (most recent call last):
  File "hypothesis-python/tests/cover/test_deadline.py", line 80, in test_deadlines_participate_in_shrinking
    slow_if_large()
  File "hypothesis-python/.tox/coverage/lib/python3.6/site-packages/_pytest/python_api.py", line 729, in __exit__
    fail(self.message)
  File "hypothesis-python/.tox/coverage/lib/python3.6/site-packages/_pytest/outcomes.py", line 116, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'hypothesis.errors.DeadlineExceeded'>
```

**Comment by Zac-HD** [comment]
For @rsokl, closed by aecb50a.
