### ISSUE TITLE
Rare datetime overflow in Django tests

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2101]
https://travis-ci.org/HypothesisWorks/hypothesis/jobs/587706185#L1065-L1114

```
+ python -m tests.django.manage test tests.django
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.............................E......................
======================================================================
You can add @seed(198172252442890527798854426654972867233) to this test to reproduce this failure.
ERROR: test_is_customer (tests.django.toystore.test_given_models.TestGetsBasicModels)
----------------------------------------------------------------------
```
```python-traceback
Traceback (most recent call last):
  File "hypothesis-python/tests/django/toystore/test_given_models.py", line 94, in test_is_customer
    @given(from_model(Customer))
  File "hypothesis/core.py", line 1005, in wrapped_test
    raise the_error_hypothesis_found
  File "django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "django/db/models/query.py", line 402, in get
    num = len(clone)
  File "django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "django/db/models/sql/compiler.py", line 1087, in execute_sql
    sql, params = self.as_sql()
  File "django/db/models/sql/compiler.py", line 489, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "django/db/models/sql/where.py", line 81, in as_sql
    sql, params = compiler.compile(child)
  File "django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "django/db/models/lookups.py", line 163, in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
  File "django/db/models/lookups.py", line 260, in process_rhs
    return super().process_rhs(compiler, connection)
  File "django/db/models/lookups.py", line 95, in process_rhs
    return self.get_db_prep_lookup(value, connection)
  File "django/db/models/lookups.py", line 187, in get_db_prep_lookup
    [get_db_prep_value(value, connection, prepared=True)]
  File "django/db/models/fields/__init__.py", line 1432, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "django/db/backends/sqlite3/operations.py", line 219, in adapt_datetimefield_value
    value = timezone.make_naive(value, self.connection.timezone)
  File "django/utils/timezone.py", line 287, in make_naive
    return value.astimezone(timezone).replace(tzinfo=None)
OverflowError: date value out of range
```

It's a rare problem, but it would be great to track this down and determine whether we need to fix the test, tighten the strategy, or report a bug upstream :smile: 

Note that because this happened on a PR which changes some internals, the listed seed will probably only reproduce this with commit 3a3909143f4eb880d12fa03bbabd9d09cfdd70aa.

**Comment by Zac-HD** [comment]
Closing this as I'm unable to reproduce it :confused:
