### ISSUE TITLE
TypeError: attrib() got an unexpected keyword argument 'convert' running hello world

### ISSUE THREAD

**Issue by juanrh** [HypothesisWorks/hypothesis#2151]
Hi, 

I'm new to this library. I was trying to write a hello world on 

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
I installed hypothesis as follows:

```bash
$ pip3 install hypothesis==4.41.3 --user
Collecting hypothesis==4.41.3
  Using cached https://files.pythonhosted.org/packages/b3/d5/55ef6ab82c7268646054194b23c98ef2566d5f07eb4d1ad85003aef8ff78/hypothesis-4.41.3-py3-none-any.whl
Collecting attrs>=19.2.0 (from hypothesis==4.41.3)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Installing collected packages: attrs, hypothesis
Successfully installed attrs-19.3.0 hypothesis-4.41.3
```

and I'm trying to run this example property:

```bash
import unittest
from hypothesis import given, seed
from hypothesis.strategies import lists,integers

class TestReverse(unittest.TestCase):
    @seed(322892837442645415338635523112211850080)
    @given(lists(integers()))
    def test_reverse_reverse(self, xs):
        # self.assertListEqual(xs[::-1][::-1], xs)
        # self.assertListEqual(xs, xs)
        pass

if __name__ == "__main__":
    unittest.main()
```

that fails with

```bash
$ python3 hypothesis/hello_hypothesis.py 
/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
E
======================================================================
ERROR: test_reverse_reverse (__main__.TestReverse)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 598, in evaluate_test_data
    result = self.execute(data)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 563, in execute
    result = self.test_runner(data, run)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
    return function(data)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 542, in run
    args, kwargs = data.draw(self.search_strategy)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 849, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 225, in do_draw
    return self.base.do_draw(data)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/collections.py", line 60, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/collections.py", line 60, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/strategies.py", line 570, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/lazy.py", line 156, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/strategies.py", line 570, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/collections.py", line 60, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/collections.py", line 60, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/lazy.py", line 156, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/collections.py", line 120, in do_draw
    result.append(data.draw(self.element_strategy))
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 834, in draw
    return self.__draw(strategy, label=label)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 843, in __draw
    return strategy.do_draw(self)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/searchstrategy/numbers.py", line 40, in do_draw
    size = self.sizes[self.distribution.sample(data)]
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/utils.py", line 337, in sample
    i = integer_range(data, 0, len(self.table) - 1)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/utils.py", line 106, in integer_range
    data.stop_example(discard=probe > gap)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 895, in stop_example
    self.mark_invalid()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 1008, in mark_invalid
    self.conclude_test(Status.INVALID)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/data.py", line 1002, in conclude_test
    raise StopTest(self.testcounter)
hypothesis.errors.StopTest: 33

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 964, in wrapped_test
    state.run()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 652, in run
    runner.run()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/engine.py", line 402, in run
    self._run()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/engine.py", line 769, in _run
    self.generate_new_examples()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/engine.py", line 753, in generate_new_examples
    self.test_function(data)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/engine.py", line 148, in test_function
    self.__stoppable_test_function(data)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/conjecture/engine.py", line 131, in __stoppable_test_function
    self._test_function(data)
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 615, in evaluate_test_data
    ) + skip_exceptions_to_reraise():
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 408, in run
    result[0] = fn()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 436, in skip_exceptions_to_reraise
    from pytest.runner import Skipped
  File "/usr/lib/python3/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hypothesis/hello_hypothesis.py", line 7, in test_reverse_reverse
    @given(lists(integers()))
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1003, in wrapped_test
    get_trimmed_traceback()
  File "/home/juanrh/.local/lib/python3.6/site-packages/hypothesis/internal/escalation.py", line 99, in get_trimmed_traceback
    is_hypothesis_file(getframeinfo(tb.tb_frame)[0])
  File "/usr/lib/python3.6/inspect.py", line 1452, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/lib/python3.6/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/usr/lib/python3.6/inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 195, in __getattribute__
    return getattr(getmod(), name)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 179, in getmod
    x = importobj(modpath, None)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "/usr/lib/python3/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'

----------------------------------------------------------------------
Ran 1 test in 0.078s

FAILED (errors=1)
```

I installed the latest version to avoid [this problem with a TypeError](https://hypothesis.readthedocs.io/en/latest/changes.html#v3-44-22) but it seems there is another issue. 

Is there any workaround to fix this? 

Thanks

**Comment by juanrh** [comment]
I tried reinstalling from apt

```bash
pip3 uninstall hypothesis
sudo apt install python3-hypothesis
```

and now it fails just when I import the module. This worked with the version from pip, where I could do things like `strategies.text().example()` in the REPL

```python
>>> import hypothesis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/hypothesis/__init__.py", line 31, in <module>
    from hypothesis.core import given, find, example, seed, reproduce_failure, \
  File "/usr/lib/python3/dist-packages/hypothesis/core.py", line 380, in <module>
    exceptions_to_reraise = skip_exceptions_to_reraise()
  File "/usr/lib/python3/dist-packages/hypothesis/core.py", line 366, in skip_exceptions_to_reraise
    from pytest.runner import Skipped
  File "/usr/lib/python3/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
>>>
```

**Comment by Zac-HD** [comment]
```python-traceback
Traceback (most recent call last):
  ...
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
```

I think you need a newer version of `pytest` too - try `pip install -U pytest`.

**Comment by juanrh** [comment]
I installed the latest version of pytest and now it works for me. I ended up with the following versions:

```python
>>> hypothesis.__version__
'4.41.3'
>>> pytest.__version__
'5.2.2'
>>> attr.__version__
'19.3.0'
```

Thanks for the quick answer!
