### ISSUE TITLE
Flaky `tests/quality/test_discovery_ability.py::test_sampled_from_often_distorted`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2163]
```python-traceback
______________________ test_sampled_from_often_distorted ______________________
Traceback (most recent call last):
  File "tests\quality\test_discovery_ability.py", line 100, in run_test
    runner.run()
  File "hypothesis\internal\conjecture\engine.py", line 371, in run
    self._run()
  File "hypothesis\internal\conjecture\engine.py", line 556, in _run
    self.generate_new_examples()
  File "hypothesis\internal\conjecture\engine.py", line 534, in generate_new_examples
    self.test_function(data)
  File "hypothesis\internal\conjecture\engine.py", line 203, in test_function
    self.record_for_health_check(data)
  File "hypothesis\internal\conjecture\engine.py", line 273, in record_for_health_check
    HealthCheck.filter_too_much,
  File "hypothesis\internal\healthcheck.py", line 36, in fail_health_check
    raise FailedHealthCheck(message, label)
hypothesis.errors.FailedHealthCheck:
	It looks like your strategy is filtering out a lot of data...
```

[Via this CI job](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=2756&view=logs&jobId=756682f3-6574-5117-ee9f-553859b37e15&taskId=2d7e3546-07bd-59f9-1646-6b9783c98d7a&lineStart=231&lineEnd=249&colStart=1&colEnd=1) for #2162.  It's a [fairly complicated condition](https://github.com/HypothesisWorks/hypothesis/blob/020df5cfc3d4ee301af799b96a8d3fa254f85ad8/hypothesis-python/tests/quality/test_discovery_ability.py#L175-L191); probably flaky due to [the engine change](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-42-0).

**Comment by Zac-HD** [comment]
No longer flaky, as far as I can tell :tada:
