### ISSUE TITLE
test_interactive_example_does_not_emit_warning fails mysteriously if virtualenv is too old

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#2167]
I was trying to run the test suite for the first time in a while, and I found that `test_interactive_example_does_not_emit_warning` (from #2104) failed mysteriously.

After some investigation, I found that the problem was caused by `site.py` in my virtualenv containing code that used deprecated features, which makes it impossible to launch `python -Werror`.

This in turn was caused by my virtualenv tool being too old (v16.0.0); apparently this issue is fixed in later versions.

**Comment by Zalathar** [comment]
I should be able to fix this locally by upgrading my virtualenv tool, and rebuilding my testing-venv.

But I might also add a note to the test in case someone else runs into the same obstacle.

**Comment by Zalathar** [comment]
Mysterious error output for anyone else searching for this issue:

```
________________ test_interactive_example_does_not_emit_warning ________________
Traceback (most recent call last):
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 500, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 176, in read_nonblocking
    raise EOF('End Of File (EOF). Empty string style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stuart/Dev/hypothesis/hypothesis-python/tests/cover/test_example.py", line 91, in test_interactive_example_does_not_emit_warning
    child.expect(">>> ", timeout=1)
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/Users/stuart/Dev/hypothesis/testing-venv/lib/python3.7/site-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
<pexpect.pty_spawn.spawn object at 0x11001dcd0>
command: /Users/stuart/Dev/hypothesis/testing-venv/bin/python3.7
args: ['/Users/stuart/Dev/hypothesis/testing-venv/bin/python3.7', '-Werror']
buffer (last 100 chars): b''
before (last 100 chars): b' line 165, in addpackage\r\n    f = open(fullname, "rU")\r\nDeprecationWarning: \'U\' mode is deprecated\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 94803
child_fd: 12
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'>>> ')
```

**Comment by Zalathar** [comment]
The upstream issue seems to have been fixed in <https://github.com/pypa/virtualenv/pull/1064>, which would explain why updating my virtualenv tool did indeed resolve the problem
