### ISSUE TITLE
Hypothesis 5.8.0 broken on Python 3.5.2

### ISSUE THREAD

**Issue by cole** [HypothesisWorks/hypothesis#2381]
Importing gives `TypeError: 'ellipsis' object is not iterable`:

```
❯ docker run -it python:3.5.2 /bin/bash -c "pip install hypothesis && python -m hypothesis"
Collecting hypothesis
  Downloading https://files.pythonhosted.org/packages/99/b4/63160b387f39a5d8c98e281f91136483245ae4d15379e72f720543122f3d/hypothesis-5.8.0-py3-none-any.whl (289kB)
    100% |████████████████████████████████| 296kB 3.6MB/s 
Collecting attrs>=19.2.0 (from hypothesis)
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting sortedcontainers<3.0.0,>=2.1.0 (from hypothesis)
  Downloading https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Installing collected packages: attrs, sortedcontainers, hypothesis
Successfully installed attrs-19.3.0 hypothesis-5.8.0 sortedcontainers-2.1.0
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.5/site-packages/hypothesis/__init__.py", line 26, in <module>
    from hypothesis.core import example, find, given, reproduce_failure, seed
  File "/usr/local/lib/python3.5/site-packages/hypothesis/core.py", line 36, in <module>
    import hypothesis.strategies as st
  File "/usr/local/lib/python3.5/site-packages/hypothesis/strategies/__init__.py", line 17, in <module>
    from hypothesis.strategies._internal.core import (
  File "/usr/local/lib/python3.5/site-packages/hypothesis/strategies/_internal/core.py", line 2248, in <module>
    ) -> SearchStrategy[Callable[..., Any]]:
  File "/usr/local/lib/python3.5/typing.py", line 1025, in __getitem__
    tvars = _type_vars(params)
  File "/usr/local/lib/python3.5/typing.py", line 284, in _type_vars
    _get_type_vars(types, tvars)
  File "/usr/local/lib/python3.5/typing.py", line 279, in _get_type_vars
    t._get_type_vars(tvars)
  File "/usr/local/lib/python3.5/typing.py", line 786, in _get_type_vars
    _get_type_vars(self.__args__, tvars)
  File "/usr/local/lib/python3.5/typing.py", line 277, in _get_type_vars
    for t in types:
TypeError: 'ellipsis' object is not iterable
```

**Comment by cole** [comment]
Possible dupe of https://github.com/HypothesisWorks/hypothesis/issues/2334?

**Comment by Zac-HD** [comment]
Related but distinct I think... but we're more likely to drop support for 3.5 than fix this I think.

**Comment by cole** [comment]
I thought that might be the case 😢. Fair enough.

**Comment by Zac-HD** [comment]
Yeah :confused: 

I'd be happy to take a patch for this, but per docs ["Hypothesis does not officially support anything except the latest patch release of any version of Python it supports"](https://hypothesis.readthedocs.io/en/latest/supported.html#python-versions).  

As context [Numpy has already dropped 3.5](https://numpy.org/neps/nep-0029-deprecation_policy.html), [the PSF will in September](https://devguide.python.org/#status-of-python-branches), and [it's only around 3% of our downloads](https://pypistats.org/packages/hypothesis) (well less than the unsupported 2.7).

**Comment by Zac-HD** [comment]
Unfortunately this looks like a known bug in Python 3.5.2 - https://github.com/python/typing/issues/259 - which we won't be able to fix :disappointed:
