### ISSUE TITLE
Flaky ghostwriter failure

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#2504]
I got this failure in #2503 and a few other places: https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=4063&view=logs&j=755e77d5-b5d4-515c-44e6-0ce24c6a6681&t=0b50e13f-3481-54d1-e48f-7bb84fae712d&l=362

```
2020-07-21T14:51:39.0290339Z __________________________ test_no_hashability_filter __________________________
2020-07-21T14:51:39.0291072Z Traceback (most recent call last):
2020-07-21T14:51:39.0292623Z   File "/home/vsts/work/1/s/hypothesis-python/tests/cover/test_ghostwriter.py", line 104, in test_no_hashability_filter
2020-07-21T14:51:39.0293450Z     test()
2020-07-21T14:51:39.0294576Z   File "/home/vsts/work/1/s/hypothesis-python/.tox/coverage/lib/python3.6/site-packages/_pytest/python_api.py", line 740, in __exit__
2020-07-21T14:51:39.0295393Z     fail(self.message)
2020-07-21T14:51:39.0296664Z   File "/home/vsts/work/1/s/hypothesis-python/.tox/coverage/lib/python3.6/site-packages/_pytest/outcomes.py", line 158, in fail
2020-07-21T14:51:39.0297506Z     raise Failed(msg=msg, pytrace=pytrace)
2020-07-21T14:51:39.0298423Z Failed: DID NOT RAISE <class 'TypeError'>
```

I haven't been able to reproduce it locally.

**Comment by Zac-HD** [comment]
Huh.  This only happens if `st.sets(st.decimals())` never generates `Decimal("snan")`, but apparently some of your changes make that more likely (odd, but it's been passing for a while otherwise :man_shrugging:).

I've added a commit to #2501 which will fix it by inspecting the ghostwritten code without trying to run it.

**Comment by DRMacIver** [comment]
> but apparently some of your changes make that more likely

Maybe! But I've seen it on unrelated branches, so I think whatever changes make it more likely are already in master.

**Comment by DRMacIver** [comment]
> I've added a commit to #2501 which will fix it by inspecting the ghostwritten code without trying to run it.

Could you separate it out as its own PR please? This is definitely in master, as I've seen it across three different unrelated pull requests now.
