### ISSUE TITLE
ghostwriter: Unhandled ValueError if inspect.signature fails

### ISSUE THREAD

**Issue by The-Compiler** [HypothesisWorks/hypothesis#2623]
When trying out the ghostwriter, I accidentally wrote `hypothesis write zip` instead of `gzip`. With Python 3.8.5 and hypothesis 5.35.3, this results in:

```pytb
Traceback (most recent call last):
  File ".venv/bin/hypothesis", line 8, in <module>
    sys.exit(main())
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/hypothesis/extra/cli.py", line 149, in write
    print(getattr(ghostwriter, writer)(*func, except_=except_ or (), style=style))
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/hypothesis/extra/ghostwriter.py", line 559, in magic
    if len(hints) == len(_get_params(func)) == 2:
  File "/home/florian/tmp/.venv/lib/python3.8/site-packages/hypothesis/extra/ghostwriter.py", line 168, in _get_params
    params = list(inspect.signature(func).parameters.values())
  File "/usr/lib/python3.8/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.8/inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.8/inspect.py", line 2372, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'zip'>
```

This should probably be handled in a nicer way - either by showing an error (e.g. via `click.UsageError`), or perhaps by writing a basic scaffolding which isn't based on the arguments. Something like:

```python
@given(
    ...  # TODO: Arguments could not be determined
)
def test_fuzz_zip(...):
    zip(...)
```

or so (with literal `...` in there).

**Comment by Zac-HD** [comment]
I'm not keen on the argument-free scaffolding idea, and to be honest I'd rather keep the tracebacks in case of error too.

We [already do some crazy things for functions in C-extensions](https://github.com/HypothesisWorks/hypothesis/blob/ea0a0c39f5b33a3f1db6fd06d861d865d0fdc130/hypothesis-python/src/hypothesis/extra/ghostwriter.py#L170-L187) though, and I guess it wouldn't be too bad to add another fallback to a hard-coded mapping of unhandled builtins to their signatures...

**Comment by Zac-HD** [comment]
Having looked into this in more depth, I think it's just out of scope: the builtins have some truly eldritch calling conventions and we can't support them with any reasonable amount of effort :cry:

**Comment by The-Compiler** [comment]
What about showing a more user-friendly error message (rather than an unhandled exception) then?
