### ISSUE TITLE
test_registered_from_entrypoint failed

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis#2633]
```
=================================== FAILURES ===================================
_______________________ test_registered_from_entrypoint ________________________
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-5.36.2/hypothesis-python/examples/example_hypothesis_entrypoint/test_entrypoint.py", line 22, in test_registered_from_entrypoint
    def test_registered_from_entrypoint(x):
  File "/build/python-hypothesis/src/hypothesis-5.36.2/hypothesis-python/tmp_install/usr/lib/python3.8/site-packages/hypothesis/core.py", line 1162, in wrapped_test
    raise the_error_hypothesis_found
  File "/build/python-hypothesis/src/hypothesis-5.36.2/hypothesis-python/examples/example_hypothesis_entrypoint/example_hypothesis_entrypoint.py", line 25, in __init__
    assert x >= 0, f"got {x}, but only positive numbers are allowed"
AssertionError: got -27269, but only positive numbers are allowed
---------------------------------- Hypothesis ----------------------------------
You can add @seed(86272599037689302272937471523060014934) to this test or run pytest with --hypothesis-seed=86272599037689302272937471523060014934 to reproduce this failure.
```

Env:
```
platform linux -- Python 3.8.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /build/python-hypothesis/src/hypothesis-5.36.2, configfile: pytest.ini
plugins: hypothesis-5.36.2, xdist-2.1.0, forked-1.3.0, flaky-3.7.0, Faker-4.1.6
```

OS: Arch Linux x86_64 latest

**Comment by Zac-HD** [comment]
Per #2567, this is an example of setuptools entrypoints - so you'll need to `pip install examples/example_hypothesis_entrypoint/` before running that test.

**Comment by felixonmars** [comment]
I see. Thanks for the info!
