### ISSUE TITLE
Better error message from one_of() when an argument isn't a strategy 

### ISSUE THREAD

**Issue by asmeurer** [HypothesisWorks/hypothesis#2638]
I wanted to create a strategy to pick an item from a fixed set of things. I tried using `one_of(list_of_items)`. But this is incorrect. The arguments to `one_of` should be strategies. What I wanted was `sample_from(list_of_items)`. It doesn't fail when creating the one_of, but does when you try to use it in another strategy like `builds`. The error message is confusing:

```py
>>> one_of([1, 2, 3])
one_of(1, 2, 3)
>>> x = one_of([1, 2, 3])
>>> builds(lambda a: a, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/core.py", line 1243, in builds
    @defines_strategy
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/core.py", line 186, in cached_strategy
    if not isinstance(result, SearchStrategy) or result.is_cacheable:
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 125, in accept
    recur(self)
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 121, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/lazy.py", line 94, in calc_is_cacheable
    if isinstance(v, SearchStrategy) and not v.is_cacheable:
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 125, in accept
    recur(self)
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 121, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 546, in calc_is_cacheable
    return all(recur(e) for e in self.original_strategies)
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 546, in <genexpr>
    return all(recur(e) for e in self.original_strategies)
  File "/Users/aaronmeurer/anaconda3/envs/array-apis/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 121, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
AttributeError: 'int' object has no attribute 'calc_is_cacheable'
```

**Comment by Zac-HD** [comment]
What version of Hypothesis are you using?  Since [version 5.36.1](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-36-1) (#2627), I get the following:

```python
>>> one_of([1, 2, 3])
Traceback (most recent call last)
    ...
InvalidArgument: Did you mean st.sampled_from([1, 2, 3])?
    st.one_of() is used to combine strategies, but all of the arguments were of other types.

**Comment by asmeurer** [comment]
I'm on 5.28.0, which is the latest version on conda-forge. It looks like conda-forge hasn't been able to auto-update the feedstock lately https://github.com/conda-forge/hypothesis-feedstock/pulls. You might want to look into that.

**Comment by Zac-HD** [comment]
Happily, @ocefpaf has since updated the feedstock and conda-forge now has the latest (5.37.1) hypothesis again!
