### ISSUE TITLE
Missing dependency on setuptools

### ISSUE THREAD

**Issue by philsc** [HypothesisWorks/hypothesis#2668]
When importing `hypothesis` in a container that only installs the declared dependencies (i.e. `sortedcontainers` and `attrs`) then we see the following error:
```
Traceback (most recent call last):
  File "/run/shm/bazel-sandbox.58afe50bce693a45c42be3530f1579c8f12116963ef7e303ad72c1a2b06ed6f2/processwrapper-sandbox/4962/execroot/__main__/bazel-out/k8-fastbuild/bin/perception/cloud/proto_format_test.runfiles/internal_pip_dependency_hypothesis/pypi__hypothesis/hypothesis/entry_points.py", line 27, in <module>
    from importlib import metadata as importlib_metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/shm/bazel-sandbox.58afe50bce693a45c42be3530f1579c8f12116963ef7e303ad72c1a2b06ed6f2/processwrapper-sandbox/4962/execroot/__main__/bazel-out/k8-fastbuild/bin/perception/cloud/proto_format_test.runfiles/internal_pip_dependency_hypothesis/pypi__hypothesis/hypothesis/entry_points.py", line 29, in <module>
    import importlib_metadata  # type: ignore  # mypy thinks this is a redefinition
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "common/python/runtime/python3_wrapper.py", line 36, in <module>
    eval(compiled_code, module.__dict__)
  File "/run/shm/bazel-sandbox.58afe50bce693a45c42be3530f1579c8f12116963ef7e303ad72c1a2b06ed6f2/processwrapper-sandbox/4962/execroot/__main__/bazel-out/k8-fastbuild/bin/perception/cloud/proto_format_test.runfiles/__main__/perception/cloud/proto_format_test.py", line 7, in <module>
    import hypothesis as hyp
  File "/run/shm/bazel-sandbox.58afe50bce693a45c42be3530f1579c8f12116963ef7e303ad72c1a2b06ed6f2/processwrapper-sandbox/4962/execroot/__main__/bazel-out/k8-fastbuild/bin/perception/cloud/proto_format_test.runfiles/internal_pip_dependency_hypothesis/pypi__hypothesis/hypothesis/__init__.py", line 27, in <module>
    from hypothesis.entry_points import run
  File "/run/shm/bazel-sandbox.58afe50bce693a45c42be3530f1579c8f12116963ef7e303ad72c1a2b06ed6f2/processwrapper-sandbox/4962/execroot/__main__/bazel-out/k8-fastbuild/bin/perception/cloud/proto_format_test.runfiles/internal_pip_dependency_hypothesis/pypi__hypothesis/hypothesis/entry_points.py", line 38, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
The `pkg_resources` module is provided by `setuptools`.

I think tweaking `setup.py` should fix it.

**Comment by Zac-HD** [comment]
Given that this only affects Python 3.6 and 3.7 (`importlib.metadata` is in the standard library from 3.8 onwards), and that depending on `setuptools` is usually a bad idea, I propose the following:

- We add a fourth (!) fallback case, which skips loading entry points on Python < 3.8 if neither `importlib_metadata` nor `setuptools` is available (and emits a warning to that effect)
- We also add a conditional dependency on the `importlib_metadata ; python_version<'3.8'` package for `hypothesis[all]`, so that dependency-insensitive users get the fast path

And as a workaround for your container, I recommend either updating Python to 3.8+, or installing `importlib_metadata`.

**Comment by philsc** [comment]
Ah, that makes sense. I didn't look closely enough. `importlib_metadata` should indeed work for our container. I'll try that, thanks!
