### ISSUE TITLE
FAILED tests/cover/test_unittest.py::test_subTest_no_self[err*] - ValueError: Invalid suffix 'tests.py' with pytest-6.2.1

### ISSUE THREAD

**Issue by mgorny** [HypothesisWorks/hypothesis#2716]
With pytest-6.2.1, the following tests start failing:

```
==================================================================== FAILURES =====================================================================
___________________________________________________________ test_subTest_no_self[err0] ____________________________________________________________
[gw2] linux -- Python 3.9.1 /usr/bin/python3.9
Traceback (most recent call last):
  File "/tmp/portage/dev-python/hypothesis-5.43.4/work/hypothesis-hypothesis-python-5.43.4/hypothesis-python-python3_9/tests/cover/test_unittest.py", line 75, in test_subTest_no_self
    fname = testdir.makefile("tests.py", SUBTEST_SUITE)
  File "/usr/lib/python3.9/site-packages/_pytest/pytester.py", line 1547, in makefile
    return py.path.local(str(self._pytester.makefile(ext, *args, **kwargs)))
  File "/usr/lib/python3.9/site-packages/_pytest/pytester.py", line 788, in makefile
    return self._makefile(ext, args, kwargs)
  File "/usr/lib/python3.9/site-packages/_pytest/pytester.py", line 756, in _makefile
    p = self.path.joinpath(basename).with_suffix(ext)
  File "/usr/lib/python3.9/pathlib.py", line 889, in with_suffix
    raise ValueError("Invalid suffix %r" % (suffix))
ValueError: Invalid suffix 'tests.py'
___________________________________________________________ test_subTest_no_self[err1] ____________________________________________________________
[gw2] linux -- Python 3.9.1 /usr/bin/python3.9
Traceback (most recent call last):
  File "/tmp/portage/dev-python/hypothesis-5.43.4/work/hypothesis-hypothesis-python-5.43.4/hypothesis-python-python3_9/tests/cover/test_unittest.py", line 75, in test_subTest_no_self
    fname = testdir.makefile("tests.py", SUBTEST_SUITE)
  File "/usr/lib/python3.9/site-packages/_pytest/pytester.py", line 1547, in makefile
    return py.path.local(str(self._pytester.makefile(ext, *args, **kwargs)))
  File "/usr/lib/python3.9/site-packages/_pytest/pytester.py", line 788, in makefile
    return self._makefile(ext, args, kwargs)
  File "/usr/lib/python3.9/site-packages/_pytest/pytester.py", line 756, in _makefile
    p = self.path.joinpath(basename).with_suffix(ext)
  File "/usr/lib/python3.9/pathlib.py", line 889, in with_suffix
    raise ValueError("Invalid suffix %r" % (suffix))
ValueError: Invalid suffix 'tests.py'
```

**Comment by Zac-HD** [comment]
This is actually an upstream regression, https://github.com/pytest-dev/pytest/issues/8192, but we'll patch it anyway.  Thanks for reporting 🙂
