### ISSUE TITLE
5.49.0: sphinx documentation generation errors and warnings

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#2745]
```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python
+ READTHEDOCS=True
+ sphinx-build -b man -d python-hypothesis hypothesis-python/docs .
Running Sphinx v3.4.2
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
WARNING: html_static_path entry '_static' is placed inside outdir
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 24 added, 0 changed, 0 removed
reading sources... [100%] usage
WARNING: autodoc: failed to import class 'ReadOnlyDatabase' from module 'hypothesis.database'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'hypothesis.database' has no attribute 'ReadOnlyDatabase'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: ReadOnlyDatabase

WARNING: autodoc: failed to import class 'MultiplexedDatabase' from module 'hypothesis.database'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'hypothesis.database' has no attribute 'MultiplexedDatabase'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: MultiplexedDatabase

WARNING: autodoc: failed to import class 'redis.RedisExampleDatabase' from module 'hypothesis.extra'; the following exception was raised:
No module named 'hypothesis.extra.redis'
WARNING: autodoc: failed to import function 'target' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'hypothesis' has no attribute 'target'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: target

WARNING: autodoc: failed to import function 'django.from_model' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import function 'django.from_form' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import function 'django.register_field_strategy' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import function 'django.from_field' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import module 'cli' from module 'hypothesis.extra'; the following exception was raised:
No module named 'hypothesis.extra.cli'
WARNING: autodoc: failed to import module 'codemods' from module 'hypothesis.extra'; the following exception was raised:
No module named 'hypothesis.extra.codemods'
WARNING: autodoc: failed to import module 'dpcontracts' from module 'hypothesis.extra'; the following exception was raised:
No module named 'dpcontracts'
WARNING: autodoc: failed to import module 'lark' from module 'hypothesis.extra'; the following exception was raised:
No module named 'lark'
WARNING: autodoc: failed to import module 'ghostwriter' from module 'hypothesis.extra'; the following exception was raised:
No module named 'hypothesis.extra.ghostwriter'
WARNING: autodoc: failed to import function 'currently_in_test_context' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'hypothesis' has no attribute 'currently_in_test_context'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: currently_in_test_context

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hypothesis.3 { quickstart details settings data extras ghostwriter django numpy healthchecks database stateful supported examples community manifesto endorsements usage strategies changes development support packaging reproducing } /usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/details.rst:689: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/settings.rst:122: WARNING: unknown document: pytest:capture
/usr/lib/python3.8/site-packages/hypothesis/strategies.py:docstring of hypothesis._strategies.builds:14: WARNING: undefined label: attrs:api_validators
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:84: WARNING: undefined label: codemods
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:293: WARNING: undefined label: hypothesis-cli
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:734: WARNING: undefined label: hypothesis-cli
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:1453: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:7605: WARNING: unknown document: numpy:reference/arrays.datetime
done
build succeeded, 24 warnings.
```

**Comment by Zac-HD** [comment]
Huh, that's not happening for me - maybe you have an older version installed.  Can you share the exact commands that you're running?

**Comment by kloczek** [comment]
> Can you share the exact commands that you're running?

Please look on top of what I've quoted. Lines with +` contains exact commnads.

Just repeated rpm package build with installed 5.49.0 and looks like there is no errors but there are still some warnings.
```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python
+ READTHEDOCS=True
+ sphinx-build -b man -d python-hypothesis hypothesis-python/docs .
Running Sphinx v3.4.2
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
WARNING: html_static_path entry '_static' is placed inside outdir
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 24 added, 0 changed, 0 removed
reading sources... [100%] usage
WARNING: autodoc: failed to import function 'django.from_model' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import function 'django.from_form' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import function 'django.register_field_strategy' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import function 'django.from_field' from module 'hypothesis.extra'; the following exception was raised:
No module named 'django'
WARNING: autodoc: failed to import module 'codemods' from module 'hypothesis.extra'; the following exception was raised:
No module named 'libcst'
WARNING: autodoc: failed to import module 'dpcontracts' from module 'hypothesis.extra'; the following exception was raised:
No module named 'dpcontracts'
WARNING: autodoc: failed to import module 'lark' from module 'hypothesis.extra'; the following exception was raised:
No module named 'lark'
WARNING: autodoc: failed to import module 'ghostwriter' from module 'hypothesis.extra'; the following exception was raised:
No module named 'black'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hypothesis.3 { quickstart details settings data extras ghostwriter django numpy healthchecks database stateful supported examples community manifesto endorsements usage strategies changes development support packaging reproducing } /usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/details.rst:689: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/settings.rst:122: WARNING: unknown document: pytest:capture
/usr/lib/python3.8/site-packages/hypothesis/strategies/__init__.py:docstring of hypothesis.strategies._internal.core.builds:14: WARNING: undefined label: attrs:api_validators
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:84: WARNING: undefined label: codemods
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:1453: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-5.49.0/hypothesis-python/docs/changes.rst:7605: WARNING: unknown document: numpy:reference/arrays.datetime
done
build succeeded, 16 warnings.
```

**Comment by Zac-HD** [comment]
Again, that works for me; I suspect you have an old version of Hypothesis installed.

**Comment by kloczek** [comment]
As I wtote second try wad with isntalled 5.49.0 (All what I have installed comes in rpm packages).

**Comment by Zac-HD** [comment]
The docs require some optional dependencies too; you can `pip install hypothesis[all]` (I don't know the rpm equivalent), or manually install the packages listed in the logs.

**Comment by Zac-HD** [comment]
We don't support invoking Sphinx via `setup.py`, nor the `-b man` option.  Try using `sphinx-build` directly?
