### ISSUE TITLE
6.13.8: build_sphinx setuptools target warnings and errors

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#2987]
Looks like something is missing
```console
[tkloczko@barrel hypothesis-python]$ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] ghostwriter
WARNING: autodoc: failed to import module 'strategies' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/usr/lib/python3.8/site-packages/hypothesis/entry_points.py", line 69, in run
    hook = entry.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1109, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pydantic/_hypothesis_plugin.py", line 78, in init pydantic._hypothesis_plugin
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1723, in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 135, in accept
    recur(self)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 131, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 92, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 112, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 159, in sampled_from
    values = check_sample(elements, "sampled_from")
  File "/usr/lib/python3.8/site-packages/hypothesis/internal/conjecture/utils.py", line 126, in check_sample
    if "numpy" in sys.modules and isinstance(values, sys.modules["numpy"].ndarray):
TypeError: isinstance() arg 2 must be a type or tuple of types

WARNING: autodoc: failed to import module 'codemods' from module 'hypothesis.extra'; the following exception was raised:
No module named 'libcst'
WARNING: autodoc: failed to import module 'dpcontracts' from module 'hypothesis.extra'; the following exception was raised:
No module named 'dpcontracts'
WARNING: autodoc: failed to import module 'ghostwriter' from module 'hypothesis.extra'; the following exception was raised:
No module named 'black'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hypothesis.3 { quickstart details settings data extras ghostwriter django numpy healthchecks database stateful supported examples community manifesto endorsements usage strategies changes development support packaging reproducing } /usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.13.8/hypothesis-python/docs/details.rst:693: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.13.8/hypothesis-python/docs/settings.rst:128: WARNING: unknown document: pytest:capture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.13.8/hypothesis-python/docs/changes.rst:682: WARNING: undefined label: codemods
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.13.8/hypothesis-python/docs/changes.rst:2051: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.13.8/hypothesis-python/docs/changes.rst:8203: WARNING: unknown document: numpy:reference/arrays.datetime
done
build succeeded, 10 warnings.

The manual pages are in build/sphinx/man.
```

**Comment by Zalathar** [comment]
For actual releases we normally build documentation via `./build.sh documentation`, which automatically takes care of setting up a virtualenv with the necessary dependencies installed.

If you're building things by hand for whatever reason, you might need to start by installing `requirements/tools.txt` in your virtualenv, to see if that fixes things.

**Comment by kloczek** [comment]
> If you're building things by hand for whatever reason, you might need to start by installing `requirements/tools.txt` in your virtualenv, to see if that fixes things.

Just checked content of that file and on first look many of those requirements are not used.
Examples:
```console
[tkloczko@barrel hypothesis-hypothesis-python-6.13.8]$ grep -r com2ann
hypothesis-python/docs/changes.rst:Thanks to Ivan Levkivskyi for :pypi:`com2ann` - with the refactoring
hypothesis-python/build/sphinx/man/python-hypothesis.3:Thanks to Ivan Levkivskyi for \fI\%com2ann\fP \- with the refactoring
grep: hypothesis-python/build/sphinx/doctrees/changes.doctree: binary file matches
requirements/tools.txt:com2ann==0.1.1

[tkloczko@barrel hypothesis-hypothesis-python-6.13.8]$ grep -r alabaster
requirements/tools.txt:alabaster==0.7.12

[tkloczko@barrel hypothesis-hypothesis-python-6.13.8]$ grep -r appdirs
requirements/tools.txt:appdirs==1.4.4
```
Nothing in the hypothesis source tree imports those module. Some of those modules are mentioned only in doc or in comments.
I think that it would be good to review and update those requirements one by one.

**Comment by Zac-HD** [comment]
They're transitive dependencies which we pin using pip-compile; tools.txt lists the depending packages on subsequent lines and our direct deps are in tools.in

**Comment by Zalathar** [comment]
I don't think there's any action we need to take here.

**Comment by kloczek** [comment]
> They're transitive dependencies which we pin using pip-compile; tools.txt lists the depending packages on subsequent lines and our direct deps are in tools.in

If you install module A using pip and that module depends on modulke B it will be automatically installed as well. Issue is that those transitive dependencies dependencies may change and looks like they've changed in meantime.
