### ISSUE TITLE
Unexpected behaviour of `broadcastable_shapes`

### ISSUE THREAD

**Issue by sayandip18** [HypothesisWorks/hypothesis#3027]
`(1,1)` is not broadcast compatible with `(2,2)` yet `extra.numpy.broadcastable_shapes` returns such value
```
>>> broadcastable_shapes((2,2),min_dims=2, max_dims=2).example()
(1, 1)
>>> x = np.ones([2,2])
>>> np.broadcast_to(x,(1,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "/home/sayandip/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/sayandip/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 125, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (1,1)

```

**Comment by rsokl** [comment]
`(1, 1)` is broadcastable with `(2, 2)` your test has the array shapes flipped

```python
>>> x = np.ones([1, 1])
>>> np.broadcast_to(x,(2, 2))
array([[1., 1.],
       [1., 1.]])
```

**Comment by sayandip18** [comment]
@rsokl There are more such instances
```python
>>> from hypothesis.extra.numpy import broadcastable_shapes
>>> broadcastable_shapes((2,2)).example()
(3, 1, 1)
```
`(3,1,1)` is not broadcast compatible with `(2,2)`

**Comment by sayandip18** [comment]
Also 
```python
>>> broadcastable_shapes((2,2), min_dims=2, max_dims=3).example()
(4, 2, 2)
>>> broadcastable_shapes((2,2), min_dims=2, max_dims=3).example()
(3, 2, 1) 

```
In the first example, contrary to what you showed, `(2,2)` is broadcastable with `(4,2,2)` but not the other way around.
In the second example, neither are compatible.

**Comment by rsokl** [comment]
All of the examples that you bring up satisfy the [rules of broadcasting](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html#Rules-of-Broadcasting)

```python
>>> np.ones((2, 2)) * np.ones((4, 2, 2))  # broadcasts to (4, 2, 2)
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

>>> np.ones((2, 2)) * np.ones((3, 2, 2))  # broadcasts to (3, 2, 2)
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])
 ```

**Comment by sayandip18** [comment]
Then why does this does not work as expected?
```python
>>> x = np.random.rand(3,1,1)
>>> np.broadcast_to(x,(2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "/home/sayandip/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/sayandip/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 125, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: input operand has more dimensions than allowed by the axis remapping
>>>
>>> x = np.random.rand(2,2)
>>> np.broadcast_to(x,(3,1,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "/home/sayandip/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/sayandip/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 125, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested
```

**Comment by rsokl** [comment]
`np.broadcast_to` does handle all cases of broadcasting. It is only appropriate for broadcasting an array to a particular target shape. There are instances, however, where both arrays must be broadcast to a new, mutually-compatible shape, e.g. `(2, 2)` and `(3, 1, 1)` must be broadcast to `(3, 2, 2)`.

The `broadcastable_shapes(in_shape)` will produce any sort of shape that broadcast-compatible with `in_shape`.  This can be verified with the more general `numpy.broadcast` function. E.g. 

```python
shape = broadcastable_shapes(shape=(2, 3)).example())
np.broadcast(np.ones(shape), np.ones((2, 3)))
```

You can adjust your usage of `broadcastable_shapes` to ensure that the shapes generated do not have more dimensions than e.g. `(2, 3)` so that the result is compatible with `np.broadcast_to`
