### ISSUE TITLE
Ghostwriter error on attrs class

### ISSUE THREAD

**Issue by gmacon** [HypothesisWorks/hypothesis#3050]
While playing around with the ghostwriter today, I got an exception like this one running it against some internal code:

```
Traceback (most recent call last):
  File "/tmp/repro/venv/bin/hypothesis", line 8, in <module>
    sys.exit(main())
  File "/tmp/repro/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/repro/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/tmp/repro/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/repro/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/repro/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/repro/venv/lib/python3.9/site-packages/hypothesis/extra/cli.py", line 242, in write
    code = getattr(ghostwriter, writer)(*func, except_=except_ or (), style=style)
  File "/tmp/repro/venv/lib/python3.9/site-packages/hypothesis/extra/ghostwriter.py", line 882, in magic
    make_(
  File "/tmp/repro/venv/lib/python3.9/site-packages/hypothesis/extra/ghostwriter.py", line 802, in make_
    imp, body = how(*args, **kwargs, except_=except_, style=style)
  File "/tmp/repro/venv/lib/python3.9/site-packages/hypothesis/extra/ghostwriter.py", line 626, in _make_test_body
    given_strategies = given_strategies or _get_strategies(
  File "/tmp/repro/venv/lib/python3.9/site-packages/hypothesis/extra/ghostwriter.py", line 409, in _get_strategies
    if strat.args:
AttributeError: 'MappedSearchStrategy' object has no attribute 'args'
```

I reduced the input to trigger this exception down to

```python
import attr

@attr.s()
class Foo:
    foo: str = attr.ib()
```

I saw this with cPython 3.9.6, attrs 21.2.0, and hypothesis master branch at hypothesis-python-6.14.5-5-g9d4da6c2f.

**Comment by Zac-HD** [comment]
Thanks - with traceback, clean reproducer, and versions this was a very easy bug to fix 😍
