### ISSUE TITLE
6.17.0: sphinx errors and warnings.

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#3073]
Despite what has been provided in https://github.com/HypothesisWorks/hypothesis/issues/2745
Doesnt matter how sphinx will be used directly or over setuptools and is it will be used to generate man output or html it peroduces exactly the same errors ans warnings.

**Comment by kloczek** [comment]
drect exrcution to generate man:
```console
[tkloczko@barrel hypothesis-python]$ sphinx-build -b man -d hypothesis docs .
Running Sphinx v4.1.2
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
WARNING: html_static_path entry '_static' is placed inside outdir
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 24 added, 0 changed, 0 removed
reading sources... [100%] usage
WARNING: autodoc: failed to import module 'strategies' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/usr/lib/python3.8/site-packages/hypothesis/entry_points.py", line 69, in run
    hook = entry.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1174, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pydantic/_hypothesis_plugin.py", line 78, in init pydantic._hypothesis_plugin
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1728, in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 135, in accept
    recur(self)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 131, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 92, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 112, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 159, in sampled_from
    values = check_sample(elements, "sampled_from")
  File "/usr/lib/python3.8/site-packages/hypothesis/internal/conjecture/utils.py", line 117, in check_sample
    if "numpy" in sys.modules and isinstance(values, sys.modules["numpy"].ndarray):
TypeError: isinstance() arg 2 must be a type or tuple of types

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hypothesis.3 { quickstart details settings data extras ghostwriter django numpy healthchecks database stateful supported examples community manifesto endorsements usage strategies changes development support packaging reproducing } /usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/details.rst:693: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/settings.rst:128: WARNING: unknown document: pytest:capture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:2248: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:8400: WARNING: unknown document: numpy:reference/arrays.datetime
done
build succeeded, 7 warnings.
```
Direct execution to henerate html
```console
[tkloczko@barrel hypothesis-python]$ sphinx-build -b html -d hypothesis docs .
Running Sphinx v4.1.2
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
WARNING: html_static_path entry '_static' is placed inside outdir
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 24 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] data
WARNING: autodoc: failed to import module 'strategies' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/usr/lib/python3.8/site-packages/hypothesis/entry_points.py", line 69, in run
    hook = entry.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1174, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pydantic/_hypothesis_plugin.py", line 78, in init pydantic._hypothesis_plugin
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1728, in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 135, in accept
    recur(self)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 131, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 92, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 112, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 159, in sampled_from
    values = check_sample(elements, "sampled_from")
  File "/usr/lib/python3.8/site-packages/hypothesis/internal/conjecture/utils.py", line 117, in check_sample
    if "numpy" in sys.modules and isinstance(values, sys.modules["numpy"].ndarray):
TypeError: isinstance() arg 2 must be a type or tuple of types

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:2248: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:8400: WARNING: unknown document: numpy:reference/arrays.datetime
/usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/details.rst:693: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/settings.rst:128: WARNING: unknown document: pytest:capture
generating indices... genindex py-modindex done
highlighting module code... [100%] hypothesis.stateful
writing additional pages... search done
copying images... [100%] ../../brand/dragonfly-rainbow.svg
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 7 warnings.
```
Using setuptools<>sphinx integration
```console
[tkloczko@barrel hypothesis-python]$ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.1.2
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] data
WARNING: autodoc: failed to import module 'strategies' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/usr/lib/python3.8/site-packages/hypothesis/entry_points.py", line 69, in run
    hook = entry.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1174, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pydantic/_hypothesis_plugin.py", line 78, in init pydantic._hypothesis_plugin
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1728, in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 135, in accept
    recur(self)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 131, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 92, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 112, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 159, in sampled_from
    values = check_sample(elements, "sampled_from")
  File "/usr/lib/python3.8/site-packages/hypothesis/internal/conjecture/utils.py", line 117, in check_sample
    if "numpy" in sys.modules and isinstance(values, sys.modules["numpy"].ndarray):
TypeError: isinstance() arg 2 must be a type or tuple of types

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hypothesis.3 { quickstart details settings data extras ghostwriter django numpy healthchecks database stateful supported examples community manifesto endorsements usage strategies changes development support packaging reproducing } /usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/details.rst:693: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/settings.rst:128: WARNING: unknown document: pytest:capture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:2248: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:8400: WARNING: unknown document: numpy:reference/arrays.datetime
done
build succeeded, 6 warnings.
```
The manual pages are in build/sphinx/man.
```console
[tkloczko@barrel hypothesis-python]$ /usr/bin/python3 setup.py build_sphinx -b html --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.1.2
making output directory... done
hoverxref extension is not fully configured. Tooltips may not work as expected. Check out the documentation for hoverxref_project and hoverxref_version configuration options.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 24 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] data
WARNING: autodoc: failed to import module 'strategies' from module 'hypothesis'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/usr/lib/python3.8/site-packages/hypothesis/entry_points.py", line 69, in run
    hook = entry.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1174, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pydantic/_hypothesis_plugin.py", line 78, in init pydantic._hypothesis_plugin
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1728, in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 135, in accept
    recur(self)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 131, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 92, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 112, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 159, in sampled_from
    values = check_sample(elements, "sampled_from")
  File "/usr/lib/python3.8/site-packages/hypothesis/internal/conjecture/utils.py", line 117, in check_sample
    if "numpy" in sys.modules and isinstance(values, sys.modules["numpy"].ndarray):
TypeError: isinstance() arg 2 must be a type or tuple of types

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:2248: WARNING: unknown document: pytest:fixture
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/changes.rst:8400: WARNING: unknown document: numpy:reference/arrays.datetime
/usr/lib/python3.8/site-packages/hypothesis/control.py:docstring of hypothesis.control.assume:1: WARNING: undefined label: python:assert
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/details.rst:693: WARNING: undefined label: pytest:mark examples
/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.17.0/hypothesis-python/docs/settings.rst:128: WARNING: unknown document: pytest:capture
generating indices... genindex py-modindex done
highlighting module code... [100%] hypothesis.stateful
writing additional pages... search done
copying images... [100%] ../../brand/dragonfly-rainbow.svg
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 6 warnings.

The HTML pages are in build/sphinx/html.
```

**Comment by Zac-HD** [comment]
If you've already done `pip install -r requirements/tools.txt`, I don't have any further ideas.

I'm sorry, but as volunteers we just don't have the capacity to support anything but the builds we actually ship ourselves.

**Comment by kloczek** [comment]
If you will at least look closer on the error messages you may see that it is not a propblem with any missing module in build env but with `hypothesis.strategies`.
Despite `sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))` line  in docs/conf.py sphinx is trying to import from system modules.

**Comment by Zac-HD** [comment]
Run it in a virtualenv then?  Again, this is *not my problem* - I'm a volunteer and you have already got more support than you've paid for.
