### ISSUE TITLE
6.29.3: test suite is failing in `tests/pytest/test_pytest_detection.py::test_plugin_does_not_import_pytest` unit

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#3173]
I'm trying to package your module as an rpm package. So I'm using the typical build, install and test cycle used on building packages from non-root account.
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

I see this issue probably since 6.28.0:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.29.3-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.29.3-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -p no:randomly -p no:twisted tests -k '   not test_should_have_correct_ordering and       not test_can_disallow_prefixes and      not test_can_generate_non_utc and   not test_can_generate_prefixes_if_allowed_and_available and     not test_datetimes_stay_within_naive_bounds and         not test_utc_is_minimal'
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.29.3, configfile: pytest.ini
plugins: hypothesis-6.29.3, shutil-1.7.0, virtualenv-1.7.0, mock-3.6.1, cov-2.12.1, anyio-3.3.4, forked-1.3.0, xdist-2.3.0, flaky-3.7.0, tornasync-0.6.0.post2, console-scripts-1.2.0, trio-0.7.0, timeout-2.0.1, asyncio-0.16.0, freezegun-0.4.2, flake8-1.0.7, pyfakefs-4.5.3
collected 4921 items / 12 deselected / 4909 selected

tests/array_api/test_argument_validation.py .........................................................................................                                [  1%]
tests/array_api/test_arrays.py .............................................xx...............                                                                        [  3%]
tests/array_api/test_from_dtype.py ..........................................                                                                                        [  3%]
tests/array_api/test_indices.py .......                                                                                                                              [  4%]
tests/array_api/test_partial_adoptors.py ..............                                                                                                              [  4%]
tests/array_api/test_pretty.py ..........................                                                                                                            [  4%]
tests/array_api/test_scalar_dtypes.py ..........                                                                                                                     [  5%]
tests/codemods/test_codemod_cli.py ...                                                                                                                               [  5%]
tests/codemods/test_codemods.py ........                                                                                                                             [  5%]
tests/conjecture/test_choice_tree.py ..........                                                                                                                      [  5%]
tests/conjecture/test_data_tree.py ............................                                                                                                      [  6%]
tests/conjecture/test_dfa.py ........................                                                                                                                [  6%]
tests/conjecture/test_engine.py ..........................................................................................................................           [  9%]
tests/conjecture/test_float_encoding.py ..............................................................................................                               [ 10%]
tests/conjecture/test_intlist.py .....                                                                                                                               [ 11%]
tests/conjecture/test_junkdrawer.py .....................                                                                                                            [ 11%]
tests/conjecture/test_lstar.py ............                                                                                                                          [ 11%]
tests/conjecture/test_minimizer.py .......                                                                                                                           [ 11%]
tests/conjecture/test_optimiser.py ..............                                                                                                                    [ 12%]
tests/conjecture/test_order_shrinking.py ....                                                                                                                        [ 12%]
tests/conjecture/test_pareto.py .........                                                                                                                            [ 12%]
tests/conjecture/test_shrinker.py ..................................                                                                                                 [ 13%]
tests/conjecture/test_shrinking_dfas.py ..........                                                                                                                   [ 13%]
tests/conjecture/test_shrinking_interface.py ...                                                                                                                     [ 13%]
tests/conjecture/test_test_data.py ...........................................                                                                                       [ 14%]
tests/conjecture/test_utils.py .....................................                                                                                                 [ 15%]
tests/cover/test_annotations.py ..................                                                                                                                   [ 15%]
tests/cover/test_arbitrary_data.py ..........                                                                                                                        [ 15%]
tests/cover/test_async_def.py .                                                                                                                                      [ 15%]
tests/cover/test_asyncio.py ss                                                                                                                                       [ 15%]
tests/cover/test_attrs_inference.py .....                                                                                                                            [ 15%]
tests/cover/test_cache_implementation.py ....................                                                                                                        [ 16%]
tests/cover/test_caching.py .......                                                                                                                                  [ 16%]
tests/cover/test_cathetus.py ......................................................................                                                                  [ 17%]
tests/cover/test_charmap.py .................                                                                                                                        [ 18%]
tests/cover/test_compat.py .................                                                                                                                         [ 18%]
tests/cover/test_complex_numbers.py ..............                                                                                                                   [ 18%]
tests/cover/test_composite.py .............                                                                                                                          [ 18%]
tests/cover/test_composite_kwonlyargs.py .                                                                                                                           [ 19%]
tests/cover/test_control.py ...............                                                                                                                          [ 19%]
tests/cover/test_core.py .........                                                                                                                                   [ 19%]
tests/cover/test_custom_reprs.py ......                                                                                                                              [ 19%]
tests/cover/test_database_backend.py ........................                                                                                                        [ 20%]
tests/cover/test_datetimes.py ......................................                                                                                                 [ 20%]
tests/cover/test_deadline.py ............                                                                                                                            [ 21%]
tests/cover/test_debug_information.py .                                                                                                                              [ 21%]
tests/cover/test_deferred_strategies.py .................                                                                                                            [ 21%]
tests/cover/test_detection.py .....                                                                                                                                  [ 21%]
tests/cover/test_direct_strategies.py .............................................................................................................................. [ 24%]
................................................................................................................................                                     [ 26%]
tests/cover/test_draw_example.py ..........................................................................................                                          [ 28%]
tests/cover/test_error_in_draw.py .                                                                                                                                  [ 28%]
tests/cover/test_escalation.py ......                                                                                                                                [ 28%]
tests/cover/test_example.py .........                                                                                                                                [ 28%]
tests/cover/test_executors.py ......                                                                                                                                 [ 29%]
tests/cover/test_explicit_examples.py ...........................                                                                                                    [ 29%]
tests/cover/test_falsifying_example_output.py ...                                                                                                                    [ 29%]
tests/cover/test_feature_flags.py .......                                                                                                                            [ 29%]
tests/cover/test_filestorage.py ....                                                                                                                                 [ 29%]
tests/cover/test_filter_rewriting.py ..................................................................................                                              [ 31%]
tests/cover/test_filtered_strategy.py ....                                                                                                                           [ 31%]
tests/cover/test_find.py .                                                                                                                                           [ 31%]
tests/cover/test_flakiness.py ....                                                                                                                                   [ 31%]
tests/cover/test_float_nastiness.py ............................................................                                                                     [ 32%]
tests/cover/test_float_utils.py .......                                                                                                                              [ 33%]
tests/cover/test_functions.py ................                                                                                                                       [ 33%]
tests/cover/test_fuzz_one_input.py .............                                                                                                                     [ 33%]
tests/cover/test_given_error_conditions.py .......                                                                                                                   [ 33%]
tests/cover/test_health_checks.py .....................                                                                                                              [ 34%]
tests/cover/test_internal_helpers.py .                                                                                                                               [ 34%]
tests/cover/test_intervalset.py .......                                                                                                                              [ 34%]
tests/cover/test_lambda_formatting.py .....................                                                                                                          [ 34%]
tests/cover/test_lazy_import.py .                                                                                                                                    [ 34%]
tests/cover/test_lookup.py ......................................................................................................................................... [ 37%]
.................................................................................................................................................................... [ 41%]
...............................................................................................................................................                      [ 43%]
tests/cover/test_lookup_py37.py xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                   [ 44%]
tests/cover/test_lookup_py38.py ..........x..x....                                                                                                                   [ 44%]
tests/cover/test_map.py ...                                                                                                                                          [ 45%]
tests/cover/test_mock.py ...                                                                                                                                         [ 45%]
tests/cover/test_nothing.py ............                                                                                                                             [ 45%]
tests/cover/test_numerics.py .......................                                                                                                                 [ 45%]
tests/cover/test_one_of.py .....                                                                                                                                     [ 45%]
tests/cover/test_permutations.py ....                                                                                                                                [ 45%]
tests/cover/test_phases.py .........                                                                                                                                 [ 46%]
tests/cover/test_pretty.py ................................................                                                                                          [ 47%]
tests/cover/test_provisional_strategies.py .....................................................                                                                     [ 48%]
tests/cover/test_random_module.py ...........                                                                                                                        [ 48%]
tests/cover/test_randoms.py .............................................s......                                                                                     [ 49%]
tests/cover/test_recursive.py .......                                                                                                                                [ 49%]
tests/cover/test_reflection.py .........................................................................                                                             [ 51%]
tests/cover/test_regex.py .......................................................................................................................................... [ 53%]
.............................                                                                                                                                        [ 54%]
tests/cover/test_regressions.py .....                                                                                                                                [ 54%]
tests/cover/test_reporting.py ........                                                                                                                               [ 54%]
tests/cover/test_reproduce_failure.py ..............                                                                                                                 [ 55%]
tests/cover/test_runner_strategy.py .......                                                                                                                          [ 55%]
tests/cover/test_sampled_from.py ......................                                                                                                              [ 55%]
tests/cover/test_scrutineer.py .                                                                                                                                     [ 55%]
tests/cover/test_searchstrategy.py .........                                                                                                                         [ 55%]
tests/cover/test_seed_printing.py ..........                                                                                                                         [ 56%]
tests/cover/test_settings.py .................................................................                                                                       [ 57%]
tests/cover/test_setup_teardown.py ........                                                                                                                          [ 57%]
tests/cover/test_shrink_budgeting.py ...                                                                                                                             [ 57%]
tests/cover/test_simple_characters.py ...............                                                                                                                [ 57%]
tests/cover/test_simple_collections.py ....................................................................                                                          [ 59%]
tests/cover/test_simple_strings.py .................                                                                                                                 [ 59%]
tests/cover/test_slices.py .......................................................                                                                                   [ 60%]
tests/cover/test_slippage.py .............                                                                                                                           [ 61%]
tests/cover/test_stateful.py ...................................................................                                                                     [ 62%]
tests/cover/test_statistical_events.py .................                                                                                                             [ 62%]
tests/cover/test_targeting.py ...........                                                                                                                            [ 63%]
tests/cover/test_testdecorators.py .......................................................                                                                           [ 64%]
tests/cover/test_text.py .                                                                                                                                           [ 64%]
tests/cover/test_traceback_elision.py ..                                                                                                                             [ 64%]
tests/cover/test_type_lookup.py .................................................................................................................................... [ 66%]
.........                                                                                                                                                            [ 67%]
tests/cover/test_type_lookup_forward_ref.py .s.......                                                                                                                [ 67%]
tests/cover/test_unicode_identifiers.py ....                                                                                                                         [ 67%]
tests/cover/test_unittest.py ....                                                                                                                                    [ 67%]
tests/cover/test_validation.py ....................................                                                                                                  [ 68%]
tests/cover/test_verbosity.py ........                                                                                                                               [ 68%]
tests/datetime/test_dateutil_timezones.py ..........                                                                                                                 [ 68%]
tests/datetime/test_pytz_timezones.py ..............                                                                                                                 [ 68%]
tests/datetime/test_zoneinfo_timezones.py ..                                                                                                                         [ 68%]
tests/ghostwriter/test_expected_output.py ...........................                                                                                                [ 69%]
tests/ghostwriter/test_ghostwriter.py ......................................................................................................                         [ 71%]
tests/ghostwriter/test_ghostwriter_cli.py ............                                                                                                               [ 71%]
tests/nocover/test_argument_validation.py ...................................................................................................................        [ 74%]
tests/nocover/test_bad_repr.py ...                                                                                                                                   [ 74%]
tests/nocover/test_baseexception.py ..................                                                                                                               [ 74%]
tests/nocover/test_boundary_exploration.py .                                                                                                                         [ 74%]
tests/nocover/test_build_signature.py ......                                                                                                                         [ 74%]
tests/nocover/test_cache_implementation.py .                                                                                                                         [ 74%]
tests/nocover/test_cacheable.py ..........                                                                                                                           [ 74%]
tests/nocover/test_characters.py ..                                                                                                                                  [ 74%]
tests/nocover/test_collective_minimization.py .............................................                                                                          [ 75%]
tests/nocover/test_compat.py .....                                                                                                                                   [ 75%]
tests/nocover/test_completion.py .                                                                                                                                   [ 75%]
tests/nocover/test_conjecture_engine.py ......                                                                                                                       [ 76%]
tests/nocover/test_conjecture_int_list.py .                                                                                                                          [ 76%]
tests/nocover/test_conjecture_utils.py ...                                                                                                                           [ 76%]
tests/nocover/test_conventions.py .                                                                                                                                  [ 76%]
tests/nocover/test_database_agreement.py .                                                                                                                           [ 76%]
tests/nocover/test_database_usage.py ......                                                                                                                          [ 76%]
tests/nocover/test_deferred_errors.py ......                                                                                                                         [ 76%]
tests/nocover/test_drypython_returns.py ....................................................                                                                         [ 77%]
tests/nocover/test_duplication.py ........                                                                                                                           [ 77%]
tests/nocover/test_dynamic_variable.py ..                                                                                                                            [ 77%]
tests/nocover/test_emails.py .                                                                                                                                       [ 77%]
tests/nocover/test_eval_as_source.py ...                                                                                                                             [ 77%]
tests/nocover/test_explore_arbitrary_languages.py .s                                                                                                                 [ 77%]
tests/nocover/test_fancy_repr.py ......                                                                                                                              [ 77%]
tests/nocover/test_filtering.py ..........                                                                                                                           [ 78%]
tests/nocover/test_find.py ......                                                                                                                                    [ 78%]
tests/nocover/test_fixtures.py .                                                                                                                                     [ 78%]
tests/nocover/test_flatmap.py ........................                                                                                                               [ 78%]
tests/nocover/test_floating.py ....................                                                                                                                  [ 79%]
tests/nocover/test_from_type_recipe.py .                                                                                                                             [ 79%]
tests/nocover/test_given_error_conditions.py .                                                                                                                       [ 79%]
tests/nocover/test_given_reuse.py ...                                                                                                                                [ 79%]
tests/nocover/test_imports.py .                                                                                                                                      [ 79%]
tests/nocover/test_integer_ranges.py .......                                                                                                                         [ 79%]
tests/nocover/test_interesting_origin.py ...                                                                                                                         [ 79%]
tests/nocover/test_labels.py ......                                                                                                                                  [ 79%]
tests/nocover/test_large_examples.py .                                                                                                                               [ 79%]
tests/nocover/test_limits.py .                                                                                                                                       [ 79%]
tests/nocover/test_lstar.py .                                                                                                                                        [ 79%]
tests/nocover/test_modify_inner_test.py ......                                                                                                                       [ 79%]
tests/nocover/test_nesting.py .                                                                                                                                      [ 79%]
tests/nocover/test_pretty_repr.py ....                                                                                                                               [ 79%]
tests/nocover/test_randomization.py ..                                                                                                                               [ 79%]
tests/nocover/test_recursive.py ........                                                                                                                             [ 80%]
tests/nocover/test_regex.py ....                                                                                                                                     [ 80%]
tests/nocover/test_regressions.py ..                                                                                                                                 [ 80%]
tests/nocover/test_reusable_values.py ........                                                                                                                       [ 80%]
tests/nocover/test_sampled_from.py .........                                                                                                                         [ 80%]
tests/nocover/test_scrutineer.py ....                                                                                                                                [ 80%]
tests/nocover/test_sets.py ...                                                                                                                                       [ 80%]
tests/nocover/test_sharing.py .......                                                                                                                                [ 80%]
tests/nocover/test_simple_numbers.py ............................................................................................................................... [ 83%]
..........................................................                                                                                                           [ 84%]
tests/nocover/test_simple_strings.py .                                                                                                                               [ 84%]
tests/nocover/test_skipping.py ..                                                                                                                                    [ 84%]
tests/nocover/test_stateful.py ......                                                                                                                                [ 84%]
tests/nocover/test_strategy_state.py .                                                                                                                               [ 84%]
tests/nocover/test_targeting.py ......                                                                                                                               [ 84%]
tests/nocover/test_testdecorators.py ...                                                                                                                             [ 84%]
tests/nocover/test_threading.py .                                                                                                                                    [ 84%]
tests/nocover/test_type_lookup_forward_ref.py ..                                                                                                                     [ 84%]
tests/nocover/test_unusual_settings_configs.py ..                                                                                                                    [ 84%]
tests/nocover/test_uuids.py .......                                                                                                                                  [ 85%]
tests/numpy/test_argument_validation.py ...............................................................................................................              [ 87%]
tests/numpy/test_deprecation.py ...                                                                                                                                  [ 87%]
tests/numpy/test_fill_values.py .....                                                                                                                                [ 87%]
tests/numpy/test_floor_ceil.py .........                                                                                                                             [ 87%]
tests/numpy/test_from_dtype.py ........................x............................                                                                                 [ 88%]
tests/numpy/test_gen_data.py .....................................................................................................                                   [ 90%]
tests/numpy/test_gufunc.py ...........................                                                                                                               [ 91%]
tests/numpy/test_import.py ..                                                                                                                                        [ 91%]
tests/numpy/test_narrow_floats.py ...............                                                                                                                    [ 91%]
tests/numpy/test_randomness.py .                                                                                                                                     [ 91%]
tests/numpy/test_sampled_from.py ..                                                                                                                                  [ 91%]
tests/pandas/test_argument_validation.py ..........................................                                                                                  [ 92%]
tests/pandas/test_data_frame.py .................                                                                                                                    [ 92%]
tests/pandas/test_indexes.py ........                                                                                                                                [ 93%]
tests/pandas/test_series.py .......                                                                                                                                  [ 93%]
tests/pytest/test_capture.py .....                                                                                                                                   [ 93%]
tests/pytest/test_checks.py .                                                                                                                                        [ 93%]
tests/pytest/test_compat.py ...                                                                                                                                      [ 93%]
tests/pytest/test_doctest.py .                                                                                                                                       [ 93%]
tests/pytest/test_fixtures.py .........                                                                                                                              [ 93%]
tests/pytest/test_mark.py ..                                                                                                                                         [ 93%]
tests/pytest/test_parametrized_db_keys.py .                                                                                                                          [ 93%]
tests/pytest/test_profiles.py ...                                                                                                                                    [ 93%]
tests/pytest/test_pytest_detection.py ..F                                                                                                                            [ 93%]
tests/pytest/test_reporting.py .                                                                                                                                     [ 93%]
tests/pytest/test_runs.py ..                                                                                                                                         [ 93%]
tests/pytest/test_seeding.py ....                                                                                                                                    [ 94%]
tests/pytest/test_skipping.py .                                                                                                                                      [ 94%]
tests/pytest/test_statistics.py .......                                                                                                                              [ 94%]
tests/quality/test_deferred_strategies.py ...                                                                                                                        [ 94%]
tests/quality/test_discovery_ability.py ................................................................................                                             [ 95%]
tests/quality/test_float_shrinking.py ........                                                                                                                       [ 96%]
tests/quality/test_integers.py .                                                                                                                                     [ 96%]
tests/quality/test_normalization.py ...................................                                                                                              [ 96%]
tests/quality/test_poisoned_lists.py ................................................                                                                                [ 97%]
tests/quality/test_poisoned_trees.py ......                                                                                                                          [ 97%]
tests/quality/test_shrink_quality.py ......................................................................                                                          [ 99%]
tests/quality/test_shrinking_order.py .                                                                                                                              [ 99%]
tests/quality/test_zig_zagging.py .                                                                                                                                  [ 99%]
tests/redis/test_redis_exampledatabase.py .....                                                                                                                      [ 99%]
tests/typing_extensions/test_backported_types.py ....................

================================================================================= FAILURES =================================================================================
____________________________________________________________________ test_plugin_does_not_import_pytest ____________________________________________________________________
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.29.3/hypothesis-python/tests/pytest/test_pytest_detection.py", line 48, in test_plugin_does_not_import_pytest
    testdir.runpytest_subprocess().assert_outcomes(passed=1)
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 583, in assert_outcomes
    assert_outcomes(
  File "/usr/lib/python3.8/site-packages/_pytest/pytester_assertions.py", line 66, in assert_outcomes
    assert obtained == expected
AssertionError: assert {'errors': 0,...pped': 0, ...} == {'errors': 0,...pped': 0, ...}
  Omitting 4 identical items, use -vv to show
  Differing items:
  {'failed': 1} != {'failed': 0}
  {'passed': 0} != {'passed': 1}
  Use -v to get the full diff
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
running: /usr/bin/python3 -mpytest --basetemp=/tmp/pytest-of-tkloczko/pytest-0/test_plugin_does_not_import_pytest0/runpytest-0
     in: /tmp/pytest-of-tkloczko/pytest-0/test_plugin_does_not_import_pytest0
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/pytest-of-tkloczko/pytest-0/test_plugin_does_not_import_pytest0
plugins: hypothesis-6.29.3, shutil-1.7.0, virtualenv-1.7.0, mock-3.6.1, cov-2.12.1, anyio-3.3.4, forked-1.3.0, xdist-2.3.0, flaky-3.7.0, tornasync-0.6.0.post2, console-scripts-1.2.0, trio-0.7.0, timeout-2.0.1, asyncio-0.16.0, freezegun-0.4.2, flake8-1.0.7, pyfakefs-4.5.3
collected 1 item

test_plugin_does_not_import_pytest.py F                                  [100%]

=================================== FAILURES ===================================
________________ test_pytest_plugin_does_not_import_hypothesis _________________

    def test_pytest_plugin_does_not_import_hypothesis():
>       assert "hypothesis" not in sys.modules
E       AssertionError: assert 'hypothesis' not in {'__future__': <module '__future__' from '/usr/lib64/python3.8/__future__.py'>, '__main__': <module 'pytest.__main__' ...'pytest.__main__' from '/usr/lib/python3.8/site-packages/pytest/__main__.py'>, '_abc': <module '_abc' (built-in)>, ...}
E        +  where {'__future__': <module '__future__' from '/usr/lib64/python3.8/__future__.py'>, '__main__': <module 'pytest.__main__' ...'pytest.__main__' from '/usr/lib/python3.8/site-packages/pytest/__main__.py'>, '_abc': <module '_abc' (built-in)>, ...} = sys.modules

test_plugin_does_not_import_pytest.py:4: AssertionError
=========================== short test summary info ============================
FAILED test_plugin_does_not_import_pytest.py::test_pytest_plugin_does_not_import_hypothesis
============================== 1 failed in 0.11s ===============================
============================================================================= warnings summary =============================================================================
hypothesis-python/tests/datetime/test_dateutil_timezones.py::test_can_generate_non_naive_time
  /usr/lib/python3.8/site-packages/dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
    warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))

hypothesis-python/tests/nocover/test_recursive.py::test_drawing_from_recursive_strategy_is_thread_safe
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-9

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.29.3/hypothesis-python/tests/nocover/test_recursive.py", line 141, in test
      @given(data=st.data())
    File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.29.3-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/core.py", line 1195, in wrapped_test
      raise the_error_hypothesis_found
    File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.29.3-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/internal/healthcheck.py", line 32, in fail_health_check
      raise FailedHealthCheck(message, label)
  hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 9 valid examples in 1.07 seconds (0 invalid ones and 3 exceeded maximum size). Try decreasing size of the data you're generating (with e.g. max_size or max_leaves parameters).
  See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================================== slowest 20 durations ===========================================================================
44.91s call     hypothesis-python/tests/numpy/test_gen_data.py::test_efficiently_generates_all_unique_array
41.32s call     hypothesis-python/tests/nocover/test_strategy_state.py::TestHypothesis::runTest
36.78s call     hypothesis-python/tests/nocover/test_pretty_repr.py::test_repr_evals_to_thing_with_same_repr
35.40s call     hypothesis-python/tests/nocover/test_targeting.py::test_targeting_can_be_disabled
29.32s call     hypothesis-python/tests/cover/test_targeting.py::test_targeting_with_following_empty
22.19s call     hypothesis-python/tests/quality/test_float_shrinking.py::test_shrinks_downwards_to_integers_when_fractional
20.82s call     hypothesis-python/tests/quality/test_float_shrinking.py::test_shrinks_downwards_to_integers
19.61s call     hypothesis-python/tests/nocover/test_stateful.py::test_bad_machines_fail[RoseTreeStateMachine]
17.65s call     hypothesis-python/tests/quality/test_discovery_ability.py::test_long_duplicates_strings
16.14s call     hypothesis-python/tests/quality/test_discovery_ability.py::test_can_produce_multi_line_strings
15.49s call     hypothesis-python/tests/cover/test_searchstrategy.py::test_example_raises_unsatisfiable_when_too_filtered
14.25s call     hypothesis-python/tests/nocover/test_stateful.py::test_bad_machines_fail[CanSwarm]
13.86s call     hypothesis-python/tests/nocover/test_targeting.py::test_targeting_increases_max_length
13.62s call     hypothesis-python/tests/numpy/test_from_dtype.py::test_infer_strategy_from_dtype
12.51s call     hypothesis-python/tests/quality/test_shrink_quality.py::test_minimize_multiple_elements_in_silly_large_int_range_min_is_not_dupe
12.15s call     hypothesis-python/tests/quality/test_discovery_ability.py::test_can_produce_large_binary_strings
11.40s call     hypothesis-python/tests/numpy/test_fill_values.py::test_does_not_reuse_distinct_integers
10.70s call     hypothesis-python/tests/cover/test_sampled_from.py::test_efficient_lists_of_tuples_first_element_sampled_from
10.66s call     hypothesis-python/tests/array_api/test_arrays.py::test_does_not_reuse_distinct_integers
10.65s call     hypothesis-python/tests/quality/test_shrink_quality.py::test_minimize_multiple_elements_in_silly_large_int_range
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/cover/test_asyncio.py:60: unconditional skip
SKIPPED [1] tests/cover/test_asyncio.py:76: unconditional skip
SKIPPED [1] tests/cover/test_randoms.py:331: randbytes not supported on this Python version
SKIPPED [1] tests/cover/test_type_lookup_forward_ref.py:72: typing in python3.6 is partially working
SKIPPED [1] tests/nocover/test_explore_arbitrary_languages.py:140: got empty parameter set ['seed', 'language'], function test_run_specific_example at /home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.29.3/hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py:139
XFAIL tests/array_api/test_arrays.py::test_is_still_unique_with_nan_fill
  NaNs not distinct
XFAIL tests/array_api/test_arrays.py::test_unique_array_with_fill_can_use_all_elements
  NaNs not distinct
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_tuple1_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_tuple2_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_tuple_variadic_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_list_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_dict_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_set_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_frozenset_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_deque_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_defaultdict_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_ordered_dict_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_counter_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_chainmap_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_iterable_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_iterator_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_generator_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_reversible_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_container_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_collection_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_callable_ellipsis
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_callable_no_args
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_collections_set_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_collections_mutableset_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_mapping_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_mutable_mapping_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_sequence_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_mutable_sequence_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_keysview_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_itemsview_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_valuesview_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_contextmanager_as_generic
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_re_match_bytes_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_re_match_str_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_re_pattern_bytes_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py37.py::test_resolving_standard_re_pattern_str_as_generic
  Requires Python 3.9 (PEP 585) or later.
XFAIL tests/cover/test_lookup_py38.py::test_simple_optional_key_is_optional
XFAIL tests/cover/test_lookup_py38.py::test_layered_optional_key_is_optional
XFAIL tests/numpy/test_from_dtype.py::test_unicode_string_dtypes_need_not_be_utf8
  mitigation for issue above
FAILED tests/pytest/test_pytest_detection.py::test_plugin_does_not_import_pytest - AssertionError: assert {'errors': 0,...pped': 0, ...} == {'errors': 0,...pped': 0, ...}
====================================== 1 failed, 4864 passed, 5 skipped, 12 deselected, 39 xfailed, 2 warnings in 2495.17s (0:41:35) =======================================
```

**Comment by Zac-HD** [comment]
I this is an expected failure due to one of the async or trio plugins importing Hypothesis; you could either test in a fresh env without them or just add it to you `-k` skiplist.  Personally, I'd just skip it.
