### ISSUE TITLE
Error when importing with python < 3.8 with importlib>=5.0.0

### ISSUE THREAD

**Issue by Gracecr** [HypothesisWorks/hypothesis#3473]
```
File "C:\...\py37\lib\site-packages\hypothesis\entry_points.py", line 32, in get_entry_points
    yield from importlib_metadata.entry_points().get("hypothesis", [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

`importlib_metadata.entry_points` [was changed](https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0) in the latest version of `importlib_metadata`. This causes an error when importing hypothesis with `python<3.8` when `importlib_metadata>=5.0.0` is installed.

To reproduce:
```
$ python37 -m pip install -U importlib_metadata hypothesis
$ python37
>>> import hypothesis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\hypothesis\__init__.py", line 61, in <module>
    run()
  File "C:\...\lib\site-packages\hypothesis\entry_points.py", line 61, in run
    for entry in get_entry_points():  # pragma: no cover
  File "C:\...\lib\site-packages\hypothesis\entry_points.py", line 32, in get_entry_points
    yield from importlib_metadata.entry_points().get("hypothesis", [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

It seems hypothesis is [not the only project](https://github.com/python/importlib_metadata/issues/409) running into this. Seems like most project have been pinning `hypothesis<5.0.0`. Adapting to the change seems to be straightforward for `hypothesis`:

`importlib_metadata.entry_points().get("hypothesis", [])` becomes `importlib_metadata.entry_points(group="hypothesis")`

It'd probably be best to `try/except` over both implementations as relying on `importlib_metadata>=5.0.0` would make `hypothesis` incompatible with a number of packages, at least until they (hopefully) update.

**Comment by Gracecr** [comment]
Never mind, looks this was fixed months ago and I've been using an old version. Whoops! Good job hypothesis devs!
