### ISSUE TITLE
Very slow Pandas test in CI `test-win (check-py37-niche)`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3552]
```python-traceback
_________________________ test_arbitrary_data_frames __________________________
[gw1] win32 -- Python 3.10.9 C:\hostedtoolcache\windows\Python\3.10.9\x64\python.exe
Traceback (most recent call last):
  File "D:\a\hypothesis\hypothesis\hypothesis-python\tests\pandas\test_data_frame.py", line 155, in test_arbitrary_data_frames
    @given(st.data())
  File "C:\hostedtoolcache\windows\Python\3.10.9\x64\lib\site-packages\hypothesis\core.py", line 1397, in wrapped_test
    raise the_error_hypothesis_found
  File "D:\a\hypothesis\hypothesis\hypothesis-python\tests\pandas\test_data_frame.py", line 1[88](https://github.com/HypothesisWorks/hypothesis/actions/runs/3958444802/jobs/6780032865#step:6:89), in test_arbitrary_data_frames
    assert len(set(values)) == len(values)
AssertionError: assert 3 == 4
 +  where 3 = len({NaT, Timestamp('1970-01-01 00:00:00'), Timestamp('1970-01-01 00:00:00.000000001')})
 +    where {NaT, Timestamp('1970-01-01 00:00:00'), Timestamp('1970-01-01 00:00:00.000000001')} = set(0                             NaT\n1   1970-01-01 00:00:00.000000000\n2   1970-01-01 00:00:00.000000001\n3                             NaT\nName: 0, dtype: datetime64[ns])
 +  and   4 = len(0                             NaT\n1   1970-01-01 00:00:00.000000000\n2   1970-01-01 00:00:00.000000001\n3                             NaT\nName: 0, dtype: datetime64[ns])
Falsifying example: test_arbitrary_data_frames(
    data=data(...),
)
Draw 1: [column(name=None, elements=from_dtype(dtype('uint8')), dtype=dtype('uint8'), fill=None, unique=False),
 column(name='0', elements=from_dtype(dtype('<M8[ns]')), dtype=dtype('<M8[ns]'), fill=None, unique=True),
 column(name='', elements=from_dtype(dtype('uint8')), dtype=dtype('uint8'), fill=None, unique=False)]

You can reproduce this example by temporarily adding @reproduce_failure('6.62.1', b'AXicY2RgYmBgBCJGIMHAysABpIEIIsjAwgCiGxiQASMyixHKQCgBACQrASU=') as a decorator on your test case
--------------------------------- Hypothesis ----------------------------------
WARNING: Hypothesis has spent more than five minutes working to shrink a failing example, and stopped because it is making very slow progress.  When you re-run your tests, shrinking will resume and may take this long before aborting again.
PLEASE REPORT THIS if you can provide a reproducing example, so that we can improve shrinking performance for everyone.
============================ slowest 20 durations =============================
282.[89](https://github.com/HypothesisWorks/hypothesis/actions/runs/3958444802/jobs/6780032865#step:6:90)s call     hypothesis-python/tests/pandas/test_data_frame.py::test_arbitrary_data_frames
```

I think I've seen this flake two or three times in the last few weeks, so we should fix it properly.  It's also just really slow and CI would finish faster if we sped it up or deleted it entirely.

**Comment by reaganjlee** [comment]
Hi! I'll look to take this on

**Comment by Zac-HD** [comment]
Oops, I think it was fixed this morning by @honno in https://github.com/HypothesisWorks/hypothesis/pull/3575/commits/520a2dfba8f0cb79431811459556882f360aa3e6 (PR https://github.com/HypothesisWorks/hypothesis/pull/3575/)!

Much appreciated though, I suggest https://github.com/HypothesisWorks/hypothesis/issues/3568 as an alternative 🙏
