### ISSUE TITLE
hypothesis.strategy.randoms() builds random modules where `random.uniform` sometimes raises `StopTest`

### ISSUE THREAD

**Issue by exarkun** [HypothesisWorks/hypothesis#3630]
After upgrading to hypothesis 6.74.1 (correction: I now see this even with hypothesis 6.54.5...) I began to see errors in my test suite with this stack trace:

```
[ERROR]
Traceback (most recent call last):
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/_zkapauthorizer/lease_maintenance.py", line 379, in go
    self._schedule()
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/_zkapauthorizer/lease_maintenance.py", line 388, in _schedule
    self.sample_interval_distribution().total_seconds(),
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/_zkapauthorizer/lease_maintenance.py", line 427, in sample_interval_distributi>
    seconds=random.uniform(
  File "<string>", line 5, in uniform
    
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/strategies/_internal/random.py", line 133, in implementation
    result = self._hypothesis_do_random(name, kwargs)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/strategies/_internal/random.py", line 242, in _hypothesis_do_random
    result = self.__data.draw(floats(a, b))
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py", line 955, in draw
    return strategy.do_draw(self)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py", line 156, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py", line 950, in draw
    return strategy.do_draw(self)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/strategies/_internal/numbers.py", line 296, in do_draw
    i = self.sampler.sample(data) if self.sampler else 0
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/utils.py", line 381, in sample
    base, alternate, alternate_chance = choice(data, self.table)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/utils.py", line 162, in choice
    return values[integer_range(data, 0, len(values) - 1)]
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/utils.py", line 113, in integer_range
    probe = data.draw_bits(
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py", line 1060, in draw_bits
    self.__check_capacity(n_bytes)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py", line 1116, in __check_capacity
    self.mark_overrun()
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py", line 1139, in mark_overrun
    self.conclude_test(Status.OVERRUN)
  File "/nix/store/zjxy4xbgbz0nh5vidz45wjds4rp70l5q-python3-3.9.16-env/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py", line 1128, in conclude_test
    raise StopTest(self.testcounter)
hypothesis.errors.StopTest: 2632
```

(edited so the traceback is from hypothesis 6.74.1 instead of an older version)

Application code is calling `random.uniform`.  It expected `random` to be like the stdlib `random` module and when run under the test suite it is given a value drawn from `hypothesis.strategies.randoms()` (using the normal `@given(...)` mechanism).

Since `hypothesis.errors.StopTest` isn't normally raised by `random.uniform` the application code is not prepared to do anything sensible with it and the test ultimately fails.

For the same reason, it seems like this `random.uniform` should not raise `StopTest`.

**Comment by exarkun** [comment]
I've got it down to

```
from hypothesis import given
from hypothesis.strategies import randoms
from testtools import TestCase
from twisted.internet.defer import Deferred

class XTests(TestCase):
    @given(randoms())
    def test_nodes_visited(self, random):
        async def go():
            random.uniform(1, 10)

        Deferred.fromCoroutine(go())
```

`Deferred.fromCoroutine` seems to be doing something relevant - I haven't managed to reproduce with its involvement yet.  My _guess_ is something to do with contextvars but it's a pretty wild guess.

I also tried replacing `testtools.TestCase` with `unittest.TestCase` to have one fewer third-party dependency but that "fixes" the problem - which is an interesting clue I guess - because `unittest.TestCase` happily interprets the exception to mean the test has passed, I guess?  I don't really know - what I see is that `StopTest` is still being raised but the `unittest.TestCase` marks it as passing.

**Comment by exarkun** [comment]
It is indeed the case that with this smaller example and the original, `use_true_random=True` makes the symptom go away.

The above reproduced for me with Twisted 22.10.0, Hypothesis 6.74.1, testtools 2.5.0, on CPython 3.10.9.

**Comment by Zac-HD** [comment]
We should probably stop using threading.local() and switch everything over to contextvars. No idea whether that would help with this specific thing though...

**Comment by exarkun** [comment]
> We should probably stop using threading.local() and switch everything over to contextvars. No idea whether that would help with this specific thing though...

Funny you should mention `threading.local`... I am working on a separate bug report that seems to be related to that.

**Comment by Zac-HD** [comment]
They've been causing a fair bit of trouble lately!  e.g. https://github.com/HypothesisWorks/hypothesis/issues/3585#issuecomment-1448864794

**Comment by Zac-HD** [comment]
Having dug into this a bit, it seems to be a bad interaction where `testtools` + `twisted` catches the `StopTest` (which is a `BaseException`) during test-case finalization rather than letting it be handled by Hypothesis.  It's not a problem with `st.randoms()`, either, but generally with test finalization if data is drawn inside a coroutine:

```python
from hypothesis import given, strategies as st
from testtools import TestCase
from twisted.internet.defer import Deferred

class XTests(TestCase):
    @given(st.data())
    def test_nodes_visited(self, data):
        async def go():
            data.draw(st.binary())

        Deferred.fromCoroutine(go())
```

There's not much I can do about that, since the framework is violating Hypothesis' "the thing I call is a sync function" assumption - it would have to be fixed by recognizing Hypothesis tests and re-wrapping them _ala_ `pytest-asyncio` or `pytest-trio` (and perhaps `pytest-twisted`?).
