### ISSUE TITLE
extract_lambda_source() fails with Python 3.12b1

### ISSUE THREAD

**Issue by lazka** [HypothesisWorks/hypothesis#3665]
A reduced example from an error I see for my project with Python 3.12b1

```python
from hypothesis.internal.reflection import extract_lambda_source

some_lambda = (
    lambda b: b)

extract_lambda_source(some_lambda)
```

fails with:

```python
Traceback (most recent call last):
  File "/home/lazka/Desktop/git/pycairo/a.py", line 7, in <module>
    extract_lambda_source(some_lambda)
  File "/home/lazka/.cache/pypoetry/virtualenvs/pycairo-T_VRM3sX-py3.12/lib/python3.12/site-packages/hypothesis/internal/reflection.py", line 312, in extract_lambda_source
    source = inspect.getsource(f)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/Desktop/git/cpython/Lib/inspect.py", line 1274, in getsource
    lines, lnum = getsourcelines(object)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/Desktop/git/cpython/Lib/inspect.py", line 1266, in getsourcelines
    return getblock(lines[lnum:]), lnum + 1
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/Desktop/git/cpython/Lib/inspect.py", line 1241, in getblock
    for _token in tokens:
  File "/home/lazka/Desktop/git/cpython/Lib/tokenize.py", line 451, in _tokenize
    for token in _generate_tokens_from_c_tokenizer(source, extra_tokens=True):
  File "/home/lazka/Desktop/git/cpython/Lib/tokenize.py", line 542, in _generate_tokens_from_c_tokenizer
    for info in c_tokenizer.TokenizerIter(source, extra_tokens=extra_tokens):
  File "<string>", line 1
    lambda b: b)
               ^
SyntaxError: unmatched ')'
```

**Comment by Zac-HD** [comment]
I think this is actually a _CPython_ bug, reproducible with:

```python
import inspect

some_lambda = (
    lambda b: b)
inspect.getsource(some_lambda)
```

Can you check this (I'm currently on vacation), and report to https://github.com/python/cpython/issues if so?

**Comment by lazka** [comment]
Thanks.

Already fixed in master it seems, and bisected to https://github.com/python/cpython/commit/41b622b1e8736bd86c8dc2e1471121d5f6a88937
