### ISSUE TITLE
6.82.0: `test_registered_from_entrypoint` and `test_make_full_patch[covering]` fail

### ISSUE THREAD

**Issue by dvzrv** [HypothesisWorks/hypothesis#3704]
Hi!

I'm currently upgrading the python-hypothesis package for Arch Linux to 6.82.0. Building from the auto-generated tarball on github I see `test_registered_from_entrypoint` and `test_make_full_patch[covering]` fail.

```
=================================== FAILURES ===================================
_______________________ test_registered_from_entrypoint ________________________
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/python-hypothesis/src/hypothesis-hypothesis-python-6.82.0/hypothesis-python/examples/example_hypothesis_entrypoint/test_entrypoint.py", line 17, in test_registered_from_entrypoint
    def test_registered_from_entrypoint(x):
                   ^^^
  File "/build/python-hypothesis/src/hypothesis-hypothesis-python-6.82.0/hypothesis-python/test_dir/usr/lib/python3.11/site-packages/hypothesis/core.py", line 1374, in wrapped_test
    raise the_error_hypothesis_found
  File "/build/python-hypothesis/src/hypothesis-hypothesis-python-6.82.0/hypothesis-python/examples/example_hypothesis_entrypoint/example_hypothesis_entrypoint.py", line 20, in __init__
    assert x >= 0, f"got {x}, but only positive numbers are allowed"
           ^^^^^^
AssertionError: got -1, but only positive numbers are allowed
________________________ test_make_full_patch[covering] ________________________
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/python-hypothesis/src/hypothesis-hypothesis-python-6.82.0/hypothesis-python/tests/patching/test_patching.py", line 142, in test_make_full_patch
    got = make_patch([triple], when=when, msg=msg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/python-hypothesis/src/hypothesis-hypothesis-python-6.82.0/hypothesis-python/test_dir/usr/lib/python3.11/site-packages/hypothesis/extra/_patching.py", line 190, in make_patch
    for fname, before, after in triples:
        ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
================================== Hypothesis ==================================
`git apply .hypothesis/patches/2023-07-25--0bb40158.patch` to add failing examples to your code.
============================= slowest 20 durations =============================
46.34s call     hypothesis-python/tests/quality/test_float_shrinking.py::test_shrinks_downwards_to_integers
27.11s call     hypothesis-python/tests/nocover/test_stateful.py::test_bad_machines_fail[CanSwarm]
22.19s call     hypothesis-python/tests/nocover/test_database_usage.py::test_respects_max_examples_in_database_usage
21.40s call     hypothesis-python/tests/cover/test_stateful.py::test_multiple_precondition_bug
9.49s call     hypothesis-python/tests/nocover/test_strategy_state.py::TestHypothesis::runTest
8.77s call     hypothesis-python/tests/nocover/test_stateful.py::test_bad_machines_fail[RoseTreeStateMachine]
7.26s call     hypothesis-python/tests/numpy/test_gen_data.py::test_efficiently_generates_all_unique_array
5.74s call     hypothesis-python/tests/nocover/test_pretty_repr.py::test_repr_evals_to_thing_with_same_repr
5.54s call     hypothesis-python/tests/nocover/test_targeting.py::test_targeting_can_be_disabled
5.43s call     hypothesis-python/tests/cover/test_stateful.py::test_removes_needless_steps
5.18s call     hypothesis-python/tests/numpy/test_from_dtype.py::test_infer_strategy_from_dtype
5.10s call     hypothesis-python/tests/nocover/test_conjecture_int_list.py::TestIntList::runTest
4.97s call     hypothesis-python/tests/quality/test_shrink_quality.py::test_minimize_multiple_elements_in_silly_large_int_range
4.68s call     hypothesis-python/tests/numpy/test_gen_data.py::test_can_generate_data_compound_dtypes
4.60s call     hypothesis-python/tests/lark/test_grammar.py::test_can_specify_start_rule[dict-dict]
4.54s call     hypothesis-python/tests/cover/test_targeting.py::test_targeting_with_following_empty
4.53s call     hypothesis-python/tests/cover/test_type_lookup.py::test_can_generate_from_all_registered_types[BaseExceptionGroup]
3.90s call     hypothesis-python/tests/quality/test_shrink_quality.py::test_minimize_multiple_elements_in_silly_large_int_range_min_is_not_dupe
3.87s call     hypothesis-python/tests/cover/test_lookup.py::test_resolves_forwardrefs_to_builtin_types[BaseExceptionGroup]
3.68s call     hypothesis-python/tests/cover/test_searchstrategy.py::test_example_raises_unsatisfiable_when_too_filtered
=========================== short test summary info ============================
FAILED examples/example_hypothesis_entrypoint/test_entrypoint.py::test_registered_from_entrypoint
FAILED tests/patching/test_patching.py::test_make_full_patch[covering] - Type...
====== 2 failed, 5671 passed, 12 skipped, 3 xfailed in 1485.34s (0:24:45) ======
```

We're building the package using:
```
  python -m build -nw
```

And testing using:
```
  local pytest_options=(
    -vv
  )
  local site_packages=$(python -c "import site; print(site.getsitepackages()[0])")

  cd $_name-$_version/$_alt_name
  python -m installer --destdir=test_dir dist/*.whl
  export PYTHONPATH="$PWD/test_dir/$site_packages:$PYTHONPATH"
  export PATH="$PWD/test_dir/usr/bin:$PATH"
  pytest "${pytest_options[@]}"
```

Full build and test logs:
[python-hypothesis-6.82.0-1-x86_64-build.log](https://github.com/HypothesisWorks/hypothesis/files/12162250/python-hypothesis-6.82.0-1-x86_64-build.log)
[python-hypothesis-6.82.0-1-x86_64-check.log](https://github.com/HypothesisWorks/hypothesis/files/12162249/python-hypothesis-6.82.0-1-x86_64-check.log)

**Comment by michel-slm** [comment]
`test_make_full_patch[covering]` fails identically on Fedora 39 too with Python 3.12.0 beta 4.

We have been disabling `test_registered_from_entrypoint` since July 2021, but I can't find the related issue. When I reenabled it it fails identically to what @dvzrv reported here

**Comment by Zac-HD** [comment]
Thanks for the report!  

Unfortunately [we don't have capacity to offer much support for downstream packagers](https://hypothesis.readthedocs.io/en/latest/packaging.html), but my guess would be that since we don't run this test on Python 3.12 in our own CI, the test might just fail consistently on that version.

In general, when you're running the tests in a different environment to us and hit a few such environment-related failures, it's totally reasonable to just skip those tests in your own build process.
