### ISSUE TITLE
6.80.1: does stateful testing support coroutine?

### ISSUE THREAD

**Issue by aliwo** [HypothesisWorks/hypothesis#3712]
Hi! hypothesis is changing my test paradigm. I want to learn more...!
but I think I encountered some error.

## My Environment

* Python 3.11
* hypothesis 6.80.1
* pytest 7.3.1
* pytest-asyncio 0.21.0

## What I want to do
I want to use async functions with `RuleBasedStateMachine`

## What I did
```py
from hypothesis.stateful import RuleBasedStateMachine, rule
from hypothesis.strategies import DrawFn, floats, integers, lists, tuples


class TotalAgree(RuleBasedStateMachine):
    total = 0
    nums: list[int] = []

    @rule(value=integers())
    async def add(self, value: int) -> None:
        # I actually want to make a async httpx call.
        self.total += value
        self.nums.append(value)
        assert self.total == sum(self.nums)


TestTotalAgree = TotalAgree.TestCase
```

`poetry run pytest test_temp.py --asyncio-mode=auto`

## What actually happened
```
Launching pytest with arguments --asyncio-mode=auto /Users/seungwonjeong/PycharmProjects/yorigin inflearn/test_temp.py --no-header --no-summary -q in /Users/seungwonjeong/PycharmProjects/yorigin inflearn

============================= test session starts ==============================
collecting ... collected 1 item
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 668, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 365, in pytest_collection_modifyitems
INTERNALERROR>     and _hypothesis_test_wraps_coroutine(function)
INTERNALERROR>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seungwonjeong/Library/Caches/pypoetry/virtualenvs/yorigin-6FNwXmMp-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 371, in _hypothesis_test_wraps_coroutine
INTERNALERROR>     return _is_coroutine(function.hypothesis.inner_test)
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^
INTERNALERROR> AttributeError: 'function' object has no attribute 'hypothesis'

============================ no tests ran in 0.28s =============================

Process finished with exit code 3

Empty suite

```

## What I checked already
* I checked https://github.com/HypothesisWorks/hypothesis/issues/3346 this one, but I was already using `asyncio-mode=auto`
* simple async function test works! but RuleBasedStateMachine won't work 😢 

could you help me? please share me some insight 🙇

**Comment by Zac-HD** [comment]
Support for async functions is entirely implemented in `pytest-asyncio` (or `pytest-trio`, etc.), rather than inside Hypothesis itself.  **Unfortunately, stateful testing does not support asyncio**.

For stateful testing, you'd need a (small) new [package like `hypothesis-trio`](https://github.com/python-trio/hypothesis-trio), which builds on [`pytest-trio`'s support](https://pytest-trio.readthedocs.io/en/stable/reference.html#integration-with-the-hypothesis-library).

In principle we could try to upstream some of this, but it seems like a tough API to design - not least because idiomatic Trio and asyncio code seem to diverge in this case - and so I'd want to see some downstream iteration before we commit to supporting something for years.
