### ISSUE TITLE
More clear behavior when passing non-strings to `note`

### ISSUE THREAD

**Issue by tybug** [HypothesisWorks/hypothesis#3843]
Consider the following:

```python
from hypothesis import *
from hypothesis.strategies import *

class A:
    pass

@given(builds(A))
def f(a):
    note(a)
    assert False

f()
```

This errors with the following traceback:
```python
Traceback (most recent call last):
  File "/Users/tybug/Desktop/Liam/coding/sandbox/__hypothesis.py", line 12, in <module>
    f()
  File "/Users/tybug/Desktop/Liam/coding/sandbox/__hypothesis.py", line 8, in f
    def f(a):
              
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1599, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1566, in wrapped_test
    state.run_engine()
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1214, in run_engine
    _raise_to_user(errors_to_report, self.settings, report_lines)
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1223, in _raise_to_user
    add_note(err, note)
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/compat.py", line 50, in add_note
    exc.add_note(note)
TypeError: note must be a str, not 'A'
```

In this case, it's relatively obvious that the `note` call is the culprit. But it may be more confusing in more complicated functions, since that information gets trimmed from the traceback.

I propose we either:
- fail early and explicitly when `note` is passed a non-str value
- automatically coerce `note(x)` to `report(str(x))` instead of `report(x)`

This came up in practice in https://github.com/HypothesisWorks/hypothesis/blob/798803ab0546ec08862d6f3f50cc70f43ab12a8b/hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py#L115-L120 (fix to come!)

**Comment by Zac-HD** [comment]
Let's use our pretty-printer for non-strings, to give a maximally-informative string form.  Thanks for spotting this!
