### ISSUE TITLE
Failing test for Django 5.0

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#4033]
I noticed this [failing here](https://github.com/HypothesisWorks/hypothesis/actions/runs/9824734332/job/27124053565#step:6:572), following https://github.com/HypothesisWorks/hypothesis/pull/4026.  cc @jams2, looks like it might be an overflow-to-integral-value kinda thing?

```python-traceback
FAIL: test_create_pizza (tests.django.toystore.test_given_models.TestModelWithGeneratedField)
Strategies are not inferred for GeneratedField.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hypothesis-python/tests/django/toystore/test_given_models.py", line 221, in test_create_pizza
    def test_create_pizza(self, pizza):
  File "hypothesis-python/tests/django/toystore/test_given_models.py", line 228, in test_create_pizza
    self.assertIsInstance(pizza.slice_area, float)
AssertionError: 119373196188958 is not an instance of <class 'float'>
Falsifying example: test_create_pizza(
    self=<tests.django.toystore.test_given_models.TestModelWithGeneratedField testMethod=test_create_pizza>,
    pizza=<Pizza: Pizza object (1)>,
)
```

**Comment by jams2** [comment]
I can reproduce the issue as follows:

```python
        @settings(max_examples=50000)
        @given(
            radius=integers(min_value=1, max_value=2147483647),
            slices=integers(min_value=2, max_value=2147483647),
        )
        @example(radius=847141279, slices=20224).xfail()
        @example(radius=1150244116, slices=50949).xfail()
        @example(radius=486575519, slices=7873).xfail()
        @example(radius=98419365, slices=7833).xfail()
        @example(radius=757100506, slices=18872).xfail()
        def test_slice_area_type(self, radius, slices):
            note(f"{radius=}, {slices=}")
            slice_area = math.pi * radius**2 / slices
            note(f"{slice_area=}")

            self.assertTrue(slice_area <= sys.float_info.max)
            pizza = Pizza.objects.create(radius=radius, slices=slices)
            self.assertIsInstance(pizza.slice_area, float)
```

```
======================================================================
FAIL: test_slice_area_type (tests.django.toystore.test_given_models.TestModelWithGeneratedField)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmunn/projects/hypothesis/hypothesis-python/tests/django/toystore/test_given_models.py", line 235, in test_slice_area_type
    @given(
  File "/home/jmunn/projects/hypothesis/hypothesis-python/.tox/django50/lib/python3.10/site-packages/hypothesis/core.py", line 1667, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/jmunn/projects/hypothesis/hypothesis-python/tests/django/toystore/test_given_models.py", line 250, in test_slice_area_type
    self.assertIsInstance(pizza.slice_area, float)
AssertionError: 137165730947368 is not an instance of <class 'float'>
Falsifying example: test_slice_area_type(
    self=<tests.django.toystore.test_given_models.TestModelWithGeneratedField testMethod=test_slice_area_type>,
    radius=421287089,
    slices=4065,
)
radius=421287089, slices=4065
slice_area=137165730947368.0
Explanation:
    These lines were always and only run by failing examples:
        /home/jmunn/.cache/hypothesis-build-runtimes/python-versions/3.10.14/lib/python3.10/unittest/case.py:1268
```

For the failing examples above, in each case `int(slice_area) == float(slice_area)`.

```
sqlite> create table gentest(
   ...>   a integer,
   ...>   b integer unsigned,
   ...>   gen_stored real generated always as ((3.141592653589793 * (POWER("a", 2))) / "b") stored,
   ...>   gen_virt   real generated always as ((3.141592653589793 * (POWER("a", 2))) / "b") virtual
   ...> );
sqlite> insert into gentest values (847141279, 20224), (1150244116, 50949), (486575519, 7873), (98419365, 7833), (757100506, 18872);
sqlite> select * from gentest ;
847141279|20224|111479369733716.0|111479369733716.0
1150244116|50949|81581981423823.0|81581981423823.0
486575519|7873|94473527237308.0|94473527237308.0
98419365|7833|3884927007811.0|3884927007811.0
757100506|18872|95419913317786.0|95419913317786.0
```

It looks like evaluating `pizza.slice_area` without first reloading the data from the database returns an int in certain circumstances:

```
> /home/jmunn/projects/hypothesis/hypothesis-python/tests/django/toystore/test_given_models.py(250)test_slice_area_type()
-> pizza = Pizza.objects.create(radius=radius, slices=slices)
(Pdb) n
> /home/jmunn/projects/hypothesis/hypothesis-python/tests/django/toystore/test_given_models.py(251)test_slice_area_type()
-> self.assertIsInstance(pizza.slice_area, float)
(Pdb) pizza.__dict__
{'_state': <django.db.models.base.ModelState object at 0x7201ca939a40>, 'id': 1, 'radius': 847141279, 'slices': 20224, 'total_area': 2.2545587734946724e+18, 'slice_area': 111479369733716}
(Pdb) pp pizza.__dict__
{'_state': <django.db.models.base.ModelState object at 0x7201ca939a40>,
 'id': 1,
 'radius': 847141279,
 'slice_area': 111479369733716,  # int
 'slices': 20224,
 'total_area': 2.2545587734946724e+18}
(Pdb) pizza.refresh_from_db(fields=["slice_area"])
(Pdb) pp pizza.__dict__
{'_state': <django.db.models.base.ModelState object at 0x7201ca939a40>,
 'id': 1,
 'radius': 847141279,
 'slice_area': 111479369733716.0,  # now a float
 'slices': 20224,
 'total_area': 2.2545587734946724e+18}
```

I'm not sure why, and it will take some digging to figure it out, but the Django docs do [state](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.GeneratedField):

> *Refresh the data*
> Since the database always computed the value, the object must be reloaded to access the new value after [save()](https://docs.djangoproject.com/en/5.0/ref/models/instances/#django.db.models.Model.save), for example, by using [refresh_from_db()](https://docs.djangoproject.com/en/5.0/ref/models/instances/#django.db.models.Model.refresh_from_db).

Calling `refresh_from_db` on the pizza instance solves the issue, I'll submit a patch.
