### ISSUE TITLE
Unclear how to ignore `hypothesis.errors.FlakyFailure`

### ISSUE THREAD

**Issue by h-vetinari** [HypothesisWorks/hypothesis#4146]
Hey 👋 

In  https://github.com/conda-forge/cython-blis-feedstock/pull/56 (and friends) I run into
```
  |   [...]
  |   File "$PREFIX/lib/python3.12/site-packages/hypothesis/core.py", line 1706, in wrapped_test
  |     raise the_error_hypothesis_found
  | hypothesis.errors.FlakyFailure: Hypothesis test_memoryview_float_notrans(A=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), B=array([-6.1035156e-05, -6.1035156e-05, -6.1035156e-05, -6.1035156e-05,
  |        -6.1035156e-05, -6.1035156e-05, -6.1035156e-05, -6.1035156e-05,
  |        -6.1035156e-05, -6.1035156e-05], dtype=float32), a_rows=491, a_cols=990, out_cols=802) produces unreliable results: Falsified on the first call but did not on a subsequent one (1 sub-exception)
  | Falsifying example: test_memoryview_float_notrans(
  |     A=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
  |     B=array([-6.1035156e-05, -6.1035156e-05, -6.1035156e-05, -6.1035156e-05,
  |            -6.1035156e-05, -6.1035156e-05, -6.1035156e-05, -6.1035156e-05,
  |            -6.1035156e-05, -6.1035156e-05], dtype=float32),
  |     a_rows=491,
  |     a_cols=990,
  |     out_cols=802,
  | )
  | Failed to reproduce exception. Expected: 
  | Traceback (most recent call last):
  |   File "$PREFIX/lib/python3.12/site-packages/blis/tests/test_gemm.py", line 75, in test_memoryview_float_notrans
  |     assert_allclose(numpy_result, C, atol=1e-3, rtol=1e-3)
  |   File "$PREFIX/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1691, in assert_allclose
  |     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  |   File "$PREFIX/lib/python3.12/contextlib.py", line 81, in inner
  |     return func(*args, **kwds)
  |            ^^^^^^^^^^^^^^^^^^^
  |   File "$PREFIX/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 889, in assert_array_compare
  |     raise AssertionError(msg)
  | AssertionError:
  | [...]
```

I've tried to search the docs and the issue tracker for how to ignore such flaky errors, but to no avail. Is this possible please?

If your first response is "it's a problem in the code being tested that needs fixing", then I understand where you're coming from, but you're mistaken.

<details>
<summary>Here's why</summary>

I help keep the lights on in conda-forge, and we have somewhat different constraints/requirements as a redistributor than what usual library developers have.

We generally _do_ want to run tests to ensure the library as packaged is functional, but we have to do so under less-than-ideal constraints. For example, we have no native hardware for `linux-aarch64` or `linux-ppc64le`, and so these run through emulation in QEMU, which itself is a source of errors.

As such, I really, really, really need to switch off flaky errors when I run hypothesis-enabled test suites. Yes, it would be great if there are no errors, and if they were fixed upstream, etc. etc. That's not how the world works though. That cython-blis PR (and predecessors) has been stuck for months because something is going wrong while testing in emulation on PPC.

As a volunteer, I'm not going to go on a bug hunt of indeterminate length to find out whether it's in cython-blis, our BLAS stack, QEMU, or some other random thing. And obviously no-one else is likely to either, which is why this branch of the numpy 2.0 migration (leading e.g. to `spacy`, which many people would like) is stuck.

So now that I'm trying to get it unstuck, I can either switch off the flaky errors (my preference), or skip the test entirely. Clearly, the latter is worse for overall testing. But if there's no way to do it in hypothesis, that's my only option.

</details>

**Comment by Zac-HD** [comment]
Unfortunately this is not a problem that can be solved inside Hypothesis - from our perspective, we found a failing test case, and then later discovered that calling that function again with the same arguments gives different results.  At that point, the options are basically to either

- decide that if we can't replay the failure, it doesn't count, or
- report the failure we have, with a `FlakyFailure` exception (because the original exception is not feasible to keep around)

The first case also seems better handled at the Pytest level, rather than in Hypothesis - either by skipping the flaky test if or when you expect failures to be uninformative, or perhaps with an `xfail(condition=flaky_situation(), strict=False, raises=FlakyFailure, reason="known flaky circumstances")` - the former is more efficient, the latter ensures that you can still have the test fail if it finds a non-flaky error.

also ❤️ for your volunteering on this, it's never as deeply appreciated as it ought to be.
