### ISSUE TITLE
Recommend `zoneinfo` / `st.timezones()` in documentation for `extra.pytz` and `extra.dateutil`

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#4161]
I've broken package with `dateutil` without `dateutil/zoneinfo/dateutil-zoneinfo.tar.gz`.
This caused that on testing `hypothesis` it failed in 4 tests/datetime/test_dateutil_timezones.py units with errors like below:
```console
_____________________________ test_utc_is_minimal ______________________________
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dateutil/zoneinfo/__init__.py", line 23, in getzoneinfofile_stream
    return BytesIO(get_data(__name__, ZONEFILENAME))
  File "/usr/lib64/python3.10/pkgutil.py", line 639, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.10/site-packages/dateutil/zoneinfo/dateutil-zoneinfo.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/usr/lib/python3.10/site-packages/_pytest/runner.py", line 241, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/python3.10/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/python3.10/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/python3.10/site-packages/_pytest/logging.py", line 850, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/python3.10/site-packages/_pytest/logging.py", line 833, in _runtest_for
    yield
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/python3.10/site-packages/_pytest/capture.py", line 878, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/python3.10/site-packages/_pytest/skipping.py", line 257, in pytest_runtest_call
    return (yield)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.10/site-packages/_pytest/runner.py", line 183, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.10/site-packages/_pytest/runner.py", line 173, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.10/site-packages/_pytest/python.py", line 1632, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.10/site-packages/_pytest/python.py", line 162, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.118.0/hypothesis-python/tests/datetime/test_dateutil_timezones.py", line 35, in test_utc_is_minimal
    assert tz.UTC is minimal(timezones())
  File "/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.118.0/hypothesis-python/tests/common/debug.py", line 29, in minimal
    definition.validate()
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.118.0-2.fc37.x86_64/usr/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py", line 426, in validate
    self.do_validate()
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.118.0-2.fc37.x86_64/usr/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py", line 137, in do_validate
    w = self.wrapped_strategy
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.118.0-2.fc37.x86_64/usr/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py", line 107, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.118.0-2.fc37.x86_64/usr/lib/python3.10/site-packages/hypothesis/extra/dateutil.py", line 56, in timezones
    (tz.gettz(t) for t in zoneinfo.get_zonefile_instance().zones),
  File "/usr/lib/python3.10/site-packages/dateutil/zoneinfo/__init__.py", line 101, in get_zonefile_instance
    zif = ZoneInfoFile(getzoneinfofile_stream())
  File "/usr/lib/python3.10/site-packages/dateutil/zoneinfo/__init__.py", line 25, in getzoneinfofile_stream
    warnings.warn(f"I/O error({e.errno}): {e.strerror}")
UserWarning: I/O error(2): No such file or directory
```
Before start fixing my `dateutil` I've realised that probably `hypothesis` shout use standard `zonenfo` module instead `dateutil.zoneinfo` 🤔

**Comment by kloczek** [comment]
Looks like `hypothesis` uses `pytz` as well which use should be replaced by standard `zoneinfo` as well
https://groups.google.com/g/django-developers/c/PtIyadoC-fI
https://peps.python.org/pep-0615/

**Comment by Zac-HD** [comment]
We [already provide `zoneinfo` timezones](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.timezones), along with extensions to support [dateutil](https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis.extra.dateutil.timezones) or [pytz](https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis.extra.pytz.timezones) timezones.

It seems appropriate to mark them as deprecated in the documentation, but given that even `pytz` is still depended on by some major libraries I think it'll be a while before we issue runtime deprecation warnings and eventually remove that code.

**Comment by kloczek** [comment]
> We [already provide `zoneinfo` timezones](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.timezones), along with extensions to support [dateutil](https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis.extra.dateutil.timezones) or [pytz](https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis.extra.pytz.timezones) timezones.

My point is that eventually it should be only support for standard `timezone` module and nothing else.

**Comment by Zac-HD** [comment]
I think there will remain legitimate reasons to use e.g. `dateutil`'s support for Windows-native timezones, but I'll certainly be happy to drop `pytz` eventually.  For now though I think there's a lot of value in making it easier to test `pytz`-using code, even though I'd like the quantity of that to shrink as quickly as possible.  (who knows, maybe pointing out bugs will help motivate the transition!)
