### ISSUE TITLE
`tests/cover/test_stateful.py::test_can_run_with_no_db - hypothesis.errors.FailedHealthCheck: Data generation is extremely slow` (using PyPy3.10)

### ISSUE THREAD

**Issue by mgorny** [HypothesisWorks/hypothesis#4176]
When running the test suite of 6.119.1 with PyPy3.10 7.3.17, I'm repeatedly getting the following failure:

```pytb
_______________________________________________________ test_can_run_with_no_db _______________________________________________________
[gw6] linux -- Python 3.10.14 /tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python-pypy3/install/usr/bin/pypy3
Traceback (most recent call last):
  File "/usr/lib/pypy3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
  File "/usr/lib/pypy3.10/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/lib/pypy3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/usr/lib/pypy3.10/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/pypy3.10/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/pypy3.10/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
    yield
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/pypy3.10/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/pypy3.10/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/pypy3.10/site-packages/_pytest/logging.py", line 846, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/pypy3.10/site-packages/_pytest/logging.py", line 829, in _runtest_for
    yield
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/pypy3.10/site-packages/_pytest/capture.py", line 880, in pytest_runtest_call
    return (yield)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/usr/lib/pypy3.10/site-packages/_pytest/skipping.py", line 257, in pytest_runtest_call
    return (yield)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/pypy3.10/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/pypy3.10/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/pypy3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/pypy3.10/site-packages/_pytest/python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python/tests/cover/test_stateful.py", line 438, in test_can_run_with_no_db
    run_state_machine_as_test(
  File "/tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python-pypy3/install/usr/lib/pypy3.10/site-packages/hypothesis/stateful.py", line 241, in run_state_machine_as_test
    run_state_machine(state_machine_factory)
  File "/tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python-pypy3/install/usr/lib/pypy3.10/site-packages/hypothesis/stateful.py", line 108, in run_state_machine
    @given(st.data())
  File "/tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python-pypy3/install/usr/lib/pypy3.10/site-packages/hypothesis/core.py", line 1758, in wrapped_test
    raise the_error_hypothesis_found
  File "/tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python-pypy3/install/usr/lib/pypy3.10/site-packages/hypothesis/internal/healthcheck.py", line 27, in fail_health_check
    raise FailedHealthCheck(message)
hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 8 valid examples in 1.01 seconds (3 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g. max_size or max_leaves parameters).
                         count | fraction |    slowest draws (seconds)
  rule:is_not_too_deep |    8  |     88%  |   0.070,  0.148,  0.157,  0.170,  0.234
    rule:none_charge   |    8  |      8%  |   0.003,  0.006,  0.009,  0.017,  0.036
      rule:charge      |    2  |      5%  |      --      --      --   0.007,  0.041
          data         |   11  |      0%  |      --      --      --      --      -- 
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
You can add @seed(238434266643627694982741388119426678757) to this test or run pytest with --hypothesis-seed=238434266643627694982741388119426678757 to reproduce this failure.
============================================================= Hypothesis ==============================================================
`git apply .hypothesis/patches/2024-11-16--2ed952ba.patch` to add failing examples to your code.
```

Not sure if it's a regression or if I'm just extremely unlucky today. I'm testing new releases daily, and I don't recall seeing a failed health check in the few past months, at least.

This is Gentoo Linux amd64. pytest header:

```pytb
========================================================= test session starts =========================================================
platform linux -- Python 3.10.14[pypy-7.3.17-final], pytest-8.3.3, pluggy-1.5.0 -- /tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python-pypy3/install/usr/bin/pypy3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1/hypothesis-python/.hypothesis/examples'))
rootdir: /tmp/portage/dev-python/hypothesis-6.119.1/work/hypothesis-hypothesis-python-6.119.1
configfile: pytest.ini
created: 12/12 workers
12 workers [3569 items]
```

**Comment by Zac-HD** [comment]
Hmm, https://github.com/HypothesisWorks/hypothesis/pull/4172/ could have slowed something down I guess?

**Comment by tybug** [comment]
Thanks for the report! This is a synthetic test-only issue due to our `_consistently_increment_time` CI fixture leading to health check fails (see https://github.com/HypothesisWorks/hypothesis/pull/4172#discussion_r1843949669). We can lower the increment even further to avoid this.

**Comment by tybug** [comment]
I've folded that change into #4175, so we can close once that merges.

**Comment by mgorny** [comment]
Thank you!
