### ISSUE TITLE
test_adds_note_showing_which_strategy and test_adds_note_showing_which_strategy_stateful fail (perhaps with new Python 3.11.

### ISSUE THREAD

**Issue by mcepl** [HypothesisWorks/hypothesis#4185]
While packaging hypothesis for a SUSE distribution I have met with this failing tests:

```
[  496s] =================================== FAILURES ===================================
[  496s] ____________________ test_adds_note_showing_which_strategy _____________________
[  496s] [gw9] linux -- Python 3.11.10 /usr/bin/python3.11
[  496s] Traceback (most recent call last):
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 55, in test_adds_note_showing_which_strategy
[  496s]     inner()
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 50, in inner
[  496s]     def inner(value: X):
[  496s]                ^^^
[  496s]   File "/usr/lib/python3.11/site-packages/hypothesis/core.py", line 1758, in wrapped_test
[  496s]     raise the_error_hypothesis_found
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 47, in __init__
[  496s]     assert y == 7
[  496s] AssertionError: assert 0 == 7
[  496s] while generating 'value' from builds(X, y=integers())
[  496s] 
[  496s] During handling of the above exception, another exception occurred:
[  496s] 
[  496s] Traceback (most recent call last):
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
[  496s]     result: Optional[TResult] = func()
[  496s]                                 ^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
[  496s]     lambda: ihook(item=item, **kwds), when=when, reraise=reraise
[  496s]             ^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
[  496s]     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
[  496s]     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
[  496s]     return outcome.get_result()
[  496s]            ^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
[  496s]     raise exc.with_traceback(exc.__traceback__)
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
[  496s]     res = hook_impl.function(*args)
[  496s]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
[  496s]     raise e
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
[  496s]     item.runtest()
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 1792, in runtest
[  496s]     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
[  496s]     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
[  496s]     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
[  496s]     raise exception.with_traceback(exception.__traceback__)
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
[  496s]     res = hook_impl.function(*args)
[  496s]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
[  496s]     result = testfunction(**testargs)
[  496s]              ^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 54, in test_adds_note_showing_which_strategy
[  496s]     with pytest.raises(AssertionError, match=f".*while generating 'value' from {rep}"):
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/python_api.py", line 995, in __exit__
[  496s]     self.excinfo.match(self.match_expr)
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/_code/code.py", line 714, in match
[  496s]     assert re.search(regexp, value), msg
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^
[  496s] AssertionError: Regex pattern did not match.
[  496s]  Regex: ".*while generating 'value' from builds\\(X,\\ y=integers\\(\\)\\)"
[  496s]  Input: 'assert 0 == 7'
[  496s] ________________ test_adds_note_showing_which_strategy_stateful ________________
[  496s] [gw9] linux -- Python 3.11.10 /usr/bin/python3.11
[  496s] Traceback (most recent call last):
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 69, in test_adds_note_showing_which_strategy_stateful
[  496s]     run_state_machine_as_test(Machine)
[  496s]   File "/usr/lib/python3.11/site-packages/hypothesis/stateful.py", line 241, in run_state_machine_as_test
[  496s]     run_state_machine(state_machine_factory)
[  496s]   File "/usr/lib/python3.11/site-packages/hypothesis/stateful.py", line 108, in run_state_machine
[  496s]     @given(st.data())
[  496s]                ^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/hypothesis/core.py", line 1758, in wrapped_test
[  496s]     raise the_error_hypothesis_found
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 59, in <lambda>
[  496s]     strategy = st.integers().map(lambda x: x / 0)
[  496s]                                            ~~^~~
[  496s] ZeroDivisionError: division by zero
[  496s] while generating 'value' from integers().map(lambda x: x / 0) for rule take_a_step
[  496s] Falsifying example:
[  496s] state = Machine()
[  496s] state.teardown()
[  496s] 
[  496s] During handling of the above exception, another exception occurred:
[  496s] 
[  496s] Traceback (most recent call last):
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
[  496s]     result: Optional[TResult] = func()
[  496s]                                 ^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
[  496s]     lambda: ihook(item=item, **kwds), when=when, reraise=reraise
[  496s]             ^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
[  496s]     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
[  496s]     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
[  496s]     return outcome.get_result()
[  496s]            ^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
[  496s]     raise exc.with_traceback(exc.__traceback__)
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
[  496s]     res = hook_impl.function(*args)
[  496s]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
[  496s]     raise e
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
[  496s]     item.runtest()
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 1792, in runtest
[  496s]     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
[  496s]     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
[  496s]     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
[  496s]     raise exception.with_traceback(exception.__traceback__)
[  496s]   File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
[  496s]     res = hook_impl.function(*args)
[  496s]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
[  496s]     result = testfunction(**testargs)
[  496s]              ^^^^^^^^^^^^^^^^^^^^^^^^
[  496s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-python-6.119.1/tests/cover/test_error_in_draw.py", line 68, in test_adds_note_showing_which_strategy_stateful
[  496s]     with pytest.raises(ZeroDivisionError, match=f".*{re.escape(msg)}"):
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/python_api.py", line 995, in __exit__
[  496s]     self.excinfo.match(self.match_expr)
[  496s]   File "/usr/lib/python3.11/site-packages/_pytest/_code/code.py", line 714, in match
[  496s]     assert re.search(regexp, value), msg
[  496s]            ^^^^^^^^^^^^^^^^^^^^^^^^
[  496s] AssertionError: Regex pattern did not match.
[  496s]  Regex: ".*while\\ generating\\ 'value'\\ from\\ integers\\(\\)\\.map\\(lambda\\ x:\\ x\\ /\\ 0\\)\\ for\\ rule\\ take_a_step"
[  496s]  Input: 'division by zero'
[  497s] ----------------------------- Captured stdout call -----------------------------
[  497s] while generating 'value' from integers().map(lambda x: x / 0) for rule take_a_step
[  497s] =============================== warnings summary ===============================
[  497s] tests/array_api/test_arrays.py::test_may_not_use_unrepresentable_elements[mock-draft-complex64-strat2-False]
[  497s] tests/array_api/test_arrays.py::test_may_not_use_unrepresentable_elements[mock-draft-complex64-strat2-True]
[  497s]   /usr/lib/python3.11/site-packages/hypothesis/extra/array_api.py:435: RuntimeWarning: overflow encountered in cast
[  497s]     result = self.xp.asarray(result_obj, dtype=self.dtype)
[  497s] 
[  497s] -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[  497s] ================================== Hypothesis ==================================
[  497s] `git apply .hypothesis/patches/2024-11-25--4f3c169e.patch` to add failing examples to your code.
[  497s] =========================== short test summary info ============================
[  497s] FAILED tests/cover/test_error_in_draw.py::test_adds_note_showing_which_strategy
[  497s] FAILED tests/cover/test_error_in_draw.py::test_adds_note_showing_which_strategy_stateful
[  497s] = 2 failed, 6147 passed, 14 skipped, 4 xfailed, 2 warnings in 490.93s (0:08:10) =
```

I have no idea, why these tests fail differently on this different distro (tests pass on openSUSE/Factory). 
[Build log](https://github.com/user-attachments/files/17908411/_log-SFLO.txt) doesn’t show any serious difference from the versions of packages required in `setup.py` and various `requirements/` documents. Using tarball `hypothesis-python-6.119.1.tar.gz` from `hypothesis-python` subdirectory of this repo.

**Comment by Zac-HD** [comment]
Looks like you're using pytest 7.4.4, which predates `pytest.raises()` support for `__notes__` ([added in pytest 8.0](https://docs.pytest.org/en/stable/changelog.html#additional-support-for-exception-groups-and-notes)), and our explicit [test jobs for old pytest versions](https://github.com/HypothesisWorks/hypothesis/blob/4a796091567d3bbd514a488bcfb36afcaf713774/hypothesis-python/tox.ini#L201-L215) execute a subset which doesn't include this test.

I'd be happy to accept a PR which skips these tests on pytest < 8; or you could skip them downstream.

**Comment by mcepl** [comment]
On Mon Nov 25, 2024 at 9:47 PM CET, Zac Hatfield-Dodds wrote:
> Looks like you're using pytest 7.4.4, which predates `pytest.raises()` support for `__notes__` ([added in pytest 8.0](https://docs.pytest.org/en/stable/changelog.html#additional-support-for-exception-groups-and-notes)), and our explicit [test jobs for old pytest versions](https://github.com/HypothesisWorks/hypothesis/blob/4a796091567d3bbd514a488bcfb36afcaf713774/hypothesis-python/tox.ini#L201-L215) execute a subset which doesn't include this test.
>
> I'd be happy to accept a PR which skips these tests on pytest < 8; or you could skip them downstream.

In the end we skip it base on the version of the distrbution, otherwise `pytest.version_tuple[0] < 8`
