### ISSUE TITLE
`from_type(collections.abc.Callable[..., None])` fails, while the `typing` version works

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#4192]
Example:

```python
>>> from hypothesis import strategies as st

>>> from typing import Callable
>>> st.from_type(Callable[[None], None]).example()
<function resolve_Callable.<locals>.<lambda> at 0x10538eb60>

>>> st.from_type(Callable[[None], None]).example()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 350, in example
    example_generating_inner_function()
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 336, in example_generating_inner_function
    @settings(
           ^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/core.py", line 1582, in wrapped_test
    arguments, kwargs, stuff = process_arguments_to_given(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/core.py", line 646, in process_arguments_to_given
    s.validate()
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 430, in validate
    self.do_validate()
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py", line 139, in do_validate
    w.validate()
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 431, in validate
    self.is_empty
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 146, in accept
    recur(self)
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 142, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/deferred.py", line 68, in calc_is_empty
    return recur(self.wrapped_strategy)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/deferred.py", line 38, in wrapped_strategy
    result = self.__definition()
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py", line 1171, in <lambda>
    lambda thing: deferred(lambda: _from_type(thing)),
                                   ^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py", line 1391, in _from_type
    return types.from_typing_type(thing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/types.py", line 550, in from_typing_type
    empty = ", ".join(repr(s) for s in strategies if s.is_empty)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/types.py", line 550, in <genexpr>
    empty = ", ".join(repr(s) for s in strategies if s.is_empty)
                                                     ^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 146, in accept
    recur(self)
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py", line 142, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py", line 85, in calc_is_empty
    return recur(self.wrapped_strategy)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py", line 103, in wrapped_strategy
    unwrapped_kwargs = {
                       ^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py", line 104, in <dictcomp>
    k: unwrap_strategies(v) for k, v in self.__kwargs.items()
       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py", line 43, in unwrap_strategies
    result = unwrap_strategies(s.wrapped_strategy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py", line 43, in unwrap_strategies
    result = unwrap_strategies(s.wrapped_strategy)
                               ^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/deferred.py", line 38, in wrapped_strategy
    result = self.__definition()
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py", line 1171, in <lambda>
    lambda thing: deferred(lambda: _from_type(thing)),
                                   ^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/returns/.venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py", line 1274, in _from_type
    raise InvalidArgument(f"{thing=} must be a type")  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hypothesis.errors.InvalidArgument: thing=None must be a type
```

This happens because `typing.Callable` and `collections.abc.Callable` have different `__args__`:

```python
>>> from typing import Callable
>>> Callable[[int], None].__args__
(<class 'int'>, <class 'NoneType'>)

>>> from collections.abc import Callable
>>> Callable[[int], None].__args__
(<class 'int'>, None)
```

Basically, `None` is `collections.abc.Callable` is the same as `types.NoneType` in `typing.Callable`

**Comment by Zac-HD** [comment]
Fixed by https://github.com/HypothesisWorks/hypothesis/pull/4193
