### ISSUE TITLE
Tidy up the tracebacks in the case of multiple failures

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis#848]
Consider the following test:

```python
#!/usr/bin/env python
# -*- encoding: utf-8

from hypothesis import given
from hypothesis.strategies import integers

@given(integers())
def test_x_is_not_integer(x):
    if x > 100:
        raise ValueError("This number is too big!")
    elif x < -100:
        raise RuntimeError("This number is too small!")
    elif isinstance(x, int):
        raise ZeroDivisionError("This number is too close to 0")
    else:
        assert False, "How did you even get here?"
```

This is the output in Hypothesis 3.25.0, and there's a lot of it:

```python-traceback
Falsifying example: test_x_is_not_integer(x=-101)
Traceback (most recent call last):
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 631, in run
    print_example=True, is_final=True
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 116, in run
    return test(*args, **kwargs)
  File "foo.py", line 12, in test_x_is_not_integer
    raise RuntimeError("This number is too small!")
RuntimeError: This number is too small!

Falsifying example: test_x_is_not_integer(x=101)
Traceback (most recent call last):
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 631, in run
    print_example=True, is_final=True
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 116, in run
    return test(*args, **kwargs)
  File "foo.py", line 10, in test_x_is_not_integer
    raise ValueError("This number is too big!")
ValueError: This number is too big!

Falsifying example: test_x_is_not_integer(x=0)
Traceback (most recent call last):
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 631, in run
    print_example=True, is_final=True
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 116, in run
    return test(*args, **kwargs)
  File "foo.py", line 14, in test_x_is_not_integer
    raise ZeroDivisionError("This number is too close to 0")
ZeroDivisionError: This number is too close to 0

Traceback (most recent call last):
  File "foo.py", line 18, in <module>
    test_x_is_not_integer()
  File "foo.py", line 8, in test_x_is_not_integer
    def test_x_is_not_integer(x):
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 774, in wrapped_test
    state.run()
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 692, in run
    len(self.falsifying_examples,)))
hypothesis.errors.MultipleFailures: Hypothesis found 3 distinct failures.
```

A bunch of Hypothesis traceback is mixed into the test. It might be nicer if we could render it as follows:

```python-traceback
Falsifying example: test_x_is_not_integer(x=-101)
Traceback (most recent call last):
  File "foo.py", line 12, in test_x_is_not_integer
    raise RuntimeError("This number is too small!")
RuntimeError: This number is too small!

Falsifying example: test_x_is_not_integer(x=101)
Traceback (most recent call last):
  File "foo.py", line 10, in test_x_is_not_integer
    raise ValueError("This number is too big!")
ValueError: This number is too big!

Falsifying example: test_x_is_not_integer(x=0)
Traceback (most recent call last):
  File "foo.py", line 14, in test_x_is_not_integer
    raise ZeroDivisionError("This number is too close to 0")
ZeroDivisionError: This number is too close to 0

Traceback (most recent call last):
  File "foo.py", line 18, in <module>
    test_x_is_not_integer()
  File "foo.py", line 8, in test_x_is_not_integer
    def test_x_is_not_integer(x):
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 774, in wrapped_test
    state.run()
  File "/Users/alexwlchan/.virtualenvs/tempenv-340c26170176d/lib/python3.6/site-packages/hypothesis/core.py", line 692, in run
    len(self.falsifying_examples,)))
hypothesis.errors.MultipleFailures: Hypothesis found 3 distinct failures.
```

So the traceback for each falsifying example starts and ends in user code.

I have no idea how hard this is to do, but it’s an idea.

**Comment by alexwlchan** [comment]
I’m not going to look at this more now, but going after the `traceback.format_exc()` lines in https://github.com/HypothesisWorks/hypothesis-python/pull/836/files#diff-a25471f82c055f3418a9461a952f1221R547 is probably a good start.

**Comment by DRMacIver** [comment]
+1 on tidying this up.

I think there are two different parts to doing this:

* The stack traces we print ourselves we'll need to filter ourselves.
* The final traceback is printed by pytest and I think we should think about just enabling traceback hiding for the entirety of core.py - we already have it in some individual methods, but I'm not sure we ever want core.py appearing in a user stack trace unless they're specifically debugging Hypothesis.

P.S. You may or may not have realised this, but that example would work even if all of the exceptions were of the same type - disambiguation is by both type and line

**Comment by Zac-HD** [comment]
Fixing this will probably be in the `run` and `execute` methods of `hypothesis.core.StateForActualGivenExecution`, or by filtering the traceback in the final `except:` block in the `evaluate_test_data` method.

I suggest starting by replacing the traceback with a completely different method, and checking that it works as you'd expect with the simple example above.

**Comment by Zac-HD** [comment]
I've tried this suggested format in #1225, and it looks good!

There is some repetition remaining though - I suspect because the outer function has been replaced by a proxy.  Two options seem reasonable:

- Detect adjacent duplicate lines and remove one (preserving longer cycles which might be real)
- Discard lines *outside* of Hypothesis calls too (ie assume that the test will not call back into our internals)

In either case the filtering should be skipped when in verbose or debug mode.

**Comment by banool** [comment]
Looking into this.

**Comment by Zac-HD** [comment]
https://vorpus.org/blog/beautiful-tracebacks-in-trio-v070/

Some really impressive work here, with a lovely example and (importantly) links to the issues and PRs where the code was designed and done.  Short tips - we'll probably want to do all of these:

- Remove unneeded stack frames at the top of a traceback before storing it to reraise later
- Implement context managers by hand, not with a decorator (and some fancy tips for this)
- Example tests for traceback frame removal
- Look at master, not PRs - they evolved a fair bit over time

But my main takeaway is that this can work *really, really well!*
